# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from barndoor.public.dlp.v1 import dlp_pb2 as barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2


class DlpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrgConfig = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/GetOrgConfig',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetOrgConfigRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.OrgConfig.FromString,
                )
        self.UpdateOrgConfig = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/UpdateOrgConfig',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.UpdateOrgConfigRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.OrgConfig.FromString,
                )
        self.ListDetectionTypes = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/ListDetectionTypes',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionTypesRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionTypesResponse.FromString,
                )
        self.GetResolvedPolicy = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/GetResolvedPolicy',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetResolvedPolicyRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetResolvedPolicyResponse.FromString,
                )
        self.ListAllowListEntries = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/ListAllowListEntries',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListAllowListEntriesRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListAllowListEntriesResponse.FromString,
                )
        self.CreateAllowListEntry = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/CreateAllowListEntry',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.CreateAllowListEntryRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.AllowListEntry.FromString,
                )
        self.DeleteAllowListEntry = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/DeleteAllowListEntry',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.DeleteAllowListEntryRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.DeleteAllowListEntryResponse.FromString,
                )
        self.ListDetectionActivity = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/ListDetectionActivity',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionActivityRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionActivityResponse.FromString,
                )
        self.GetActivityAggregations = channel.unary_unary(
                '/barndoor.dlp.v1.DlpService/GetActivityAggregations',
                request_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetActivityAggregationsRequest.SerializeToString,
                response_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetActivityAggregationsResponse.FromString,
                )


class DlpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrgConfig(self, request, context):
        """── Org Configuration ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrgConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDetectionTypes(self, request, context):
        """── Detection Type Registry ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResolvedPolicy(self, request, context):
        """── Resolved Policy (admin — includes attribution) ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllowListEntries(self, request, context):
        """── Allow List ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAllowListEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllowListEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDetectionActivity(self, request, context):
        """── Detection Activity (backed by OpenSearch) ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivityAggregations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DlpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrgConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrgConfig,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetOrgConfigRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.OrgConfig.SerializeToString,
            ),
            'UpdateOrgConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrgConfig,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.UpdateOrgConfigRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.OrgConfig.SerializeToString,
            ),
            'ListDetectionTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDetectionTypes,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionTypesRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionTypesResponse.SerializeToString,
            ),
            'GetResolvedPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResolvedPolicy,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetResolvedPolicyRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetResolvedPolicyResponse.SerializeToString,
            ),
            'ListAllowListEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllowListEntries,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListAllowListEntriesRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListAllowListEntriesResponse.SerializeToString,
            ),
            'CreateAllowListEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAllowListEntry,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.CreateAllowListEntryRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.AllowListEntry.SerializeToString,
            ),
            'DeleteAllowListEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllowListEntry,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.DeleteAllowListEntryRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.DeleteAllowListEntryResponse.SerializeToString,
            ),
            'ListDetectionActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDetectionActivity,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionActivityRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionActivityResponse.SerializeToString,
            ),
            'GetActivityAggregations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivityAggregations,
                    request_deserializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetActivityAggregationsRequest.FromString,
                    response_serializer=barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetActivityAggregationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barndoor.dlp.v1.DlpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DlpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrgConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/GetOrgConfig',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetOrgConfigRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.OrgConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateOrgConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/UpdateOrgConfig',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.UpdateOrgConfigRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.OrgConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDetectionTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/ListDetectionTypes',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionTypesRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionTypesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResolvedPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/GetResolvedPolicy',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetResolvedPolicyRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetResolvedPolicyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAllowListEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/ListAllowListEntries',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListAllowListEntriesRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListAllowListEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAllowListEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/CreateAllowListEntry',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.CreateAllowListEntryRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.AllowListEntry.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAllowListEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/DeleteAllowListEntry',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.DeleteAllowListEntryRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.DeleteAllowListEntryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDetectionActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/ListDetectionActivity',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionActivityRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.ListDetectionActivityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActivityAggregations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barndoor.dlp.v1.DlpService/GetActivityAggregations',
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetActivityAggregationsRequest.SerializeToString,
            barndoor_dot_public_dot_dlp_dot_v1_dot_dlp__pb2.GetActivityAggregationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
