# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from barndoor.models.agent_runtime_capabilities import AgentRuntimeCapabilities
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentRuntimeProfile(BaseModel):
    """
    A profile joined with the contract of its `current_version`.
    """ # noqa: E501
    active: StrictBool
    capabilities: AgentRuntimeCapabilities
    client: StrictStr
    config: Dict[str, StrictStr]
    created_at: datetime
    display_name: StrictStr
    id: UUID
    is_org_default: StrictBool
    org_id: UUID
    slug: StrictStr
    updated_at: datetime
    version: StrictInt = Field(description="The immutable version whose `config` is loaded below.")
    __properties: ClassVar[List[str]] = ["active", "capabilities", "client", "config", "created_at", "display_name", "id", "is_org_default", "org_id", "slug", "updated_at", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentRuntimeProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of capabilities
        if self.capabilities:
            _dict['capabilities'] = self.capabilities.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentRuntimeProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "capabilities": AgentRuntimeCapabilities.from_dict(obj["capabilities"]) if obj.get("capabilities") is not None else None,
            "client": obj.get("client"),
            "config": obj.get("config"),
            "created_at": obj.get("created_at"),
            "display_name": obj.get("display_name"),
            "id": obj.get("id"),
            "is_org_default": obj.get("is_org_default"),
            "org_id": obj.get("org_id"),
            "slug": obj.get("slug"),
            "updated_at": obj.get("updated_at"),
            "version": obj.get("version")
        })
        return _obj


