# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.api_key_kind import ApiKeyKind
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApiKey(BaseModel):
    """
    ApiKey
    """ # noqa: E501
    created_at: datetime
    created_by_user_id: UUID
    disabled_at: Optional[datetime] = Field(default=None, description="When this key was temporarily disabled. Unlike `revoked_at` this is reversible: the auth path rejects the key while set, but re-enabling (clearing it) restores access without re-issuing the secret.")
    expires_at: Optional[datetime] = None
    group_name: Optional[StrictStr] = Field(default=None, description="Optional explicit IdP group binding for this key. NULL means no explicit group; the key still inherits the assigned user's IdP groups at request time for governance scope matching.")
    id: UUID
    key_prefix: StrictStr
    kind: ApiKeyKind = Field(description="Category of credential (BCP-3510). Set at insert, never updated.")
    last_used_at: Optional[datetime] = Field(default=None, description="When this key last authenticated a request. `None` means it has never been used. Updated best-effort and throttled on the auth path (see `touch_last_used`), so it is accurate to within `last_used_min_interval`.")
    name: StrictStr
    org_id: UUID
    revoked_at: Optional[datetime] = None
    scopes: List[StrictStr]
    user_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["created_at", "created_by_user_id", "disabled_at", "expires_at", "group_name", "id", "key_prefix", "kind", "last_used_at", "name", "org_id", "revoked_at", "scopes", "user_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if disabled_at (nullable) is None
        # and model_fields_set contains the field
        if self.disabled_at is None and "disabled_at" in self.model_fields_set:
            _dict['disabled_at'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if group_name (nullable) is None
        # and model_fields_set contains the field
        if self.group_name is None and "group_name" in self.model_fields_set:
            _dict['group_name'] = None

        # set to None if last_used_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_at is None and "last_used_at" in self.model_fields_set:
            _dict['last_used_at'] = None

        # set to None if revoked_at (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_at is None and "revoked_at" in self.model_fields_set:
            _dict['revoked_at'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "created_by_user_id": obj.get("created_by_user_id"),
            "disabled_at": obj.get("disabled_at"),
            "expires_at": obj.get("expires_at"),
            "group_name": obj.get("group_name"),
            "id": obj.get("id"),
            "key_prefix": obj.get("key_prefix"),
            "kind": obj.get("kind"),
            "last_used_at": obj.get("last_used_at"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "revoked_at": obj.get("revoked_at"),
            "scopes": obj.get("scopes"),
            "user_id": obj.get("user_id")
        })
        return _obj
