# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppType(str, Enum):
    """
    Supported OAuth application types.  Values mirror Auth0's ``app_type`` field; the same values are used internally for Keycloak (which has no native ``app_type`` concept).
    """

    """
    allowed enum values
    """
    REGULAR_WEB = 'regular_web'
    SPA = 'spa'
    NATIVE = 'native'
    NON_INTERACTIVE = 'non_interactive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppType from a JSON string"""
        return cls(json.loads(json_str))


