# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BillingReason(str, Enum):
    """
    How the vendor bills a provider. Persisted as a nullable `VARCHAR(16)`, required when `billing_mode = 'not_metered'` and optional otherwise (V69 CHECK-enforced).  **Independent of [`BillingMode`], not paired with it.** A subscription that bills overages beyond the plan is genuinely per-token *and* genuinely a subscription; requiring the two to agree made that unrepresentable. What survives is the half worth keeping: a provider must not stop recording cost without saying why.  **Label only — nothing branches on this.** That is the point of separating it from [`BillingMode`]: adding a reason touches this enum, its label maps and the CHECK constraint, and never the billing path. If a proposed category needs different *behaviour* (prepaid credits drawing down a balance, committed spend needing a floor), it is a feature, not a variant here.
    """

    """
    allowed enum values
    """
    SUBSCRIPTION = 'subscription'
    LOCAL = 'local'
    EXTERNAL = 'external'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BillingReason from a JSON string"""
        return cls(json.loads(json_str))
