# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from barndoor.models.budget_limit_kind import BudgetLimitKind
from barndoor.models.budget_target_kind import BudgetTargetKind
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BudgetTargetStatus(BaseModel):
    """
    Per-mapping annotation: a budget that is currently blocking traffic for the (provider, upstream, alias) the mapping resolves to. Serialised as `budget_status` on each listing row.
    """ # noqa: E501
    budget_id: Optional[UUID] = Field(description="Filter to one policy")
    budget_name: Optional[StrictStr] = Field(description="Optional return URL for redirecting the user after connection completes.")
    kind: BudgetTargetKind
    limit_kind: BudgetLimitKind
    message: StrictStr = Field(description="Short human-readable summary suitable for a tooltip / pill label.")
    percentage_used: Union[StrictFloat, StrictInt]
    period: Optional[StrictStr] = Field(description="Optional return URL for redirecting the user after connection completes.")
    __properties: ClassVar[List[str]] = ["budget_id", "budget_name", "kind", "limit_kind", "message", "percentage_used", "period"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BudgetTargetStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if budget_id (nullable) is None
        # and model_fields_set contains the field
        if self.budget_id is None and "budget_id" in self.model_fields_set:
            _dict['budget_id'] = None

        # set to None if budget_name (nullable) is None
        # and model_fields_set contains the field
        if self.budget_name is None and "budget_name" in self.model_fields_set:
            _dict['budget_name'] = None

        # set to None if period (nullable) is None
        # and model_fields_set contains the field
        if self.period is None and "period" in self.model_fields_set:
            _dict['period'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BudgetTargetStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "budget_id": obj.get("budget_id"),
            "budget_name": obj.get("budget_name"),
            "kind": obj.get("kind"),
            "limit_kind": obj.get("limit_kind"),
            "message": obj.get("message"),
            "percentage_used": obj.get("percentage_used"),
            "period": obj.get("period")
        })
        return _obj
