# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Connection(BaseModel):
    """
    Every column of `llm_gw.connections`, plus one derived field.  Serialized straight to the admin API — there is no separate response type, which is safe because no column here holds key material. `secret_path` is a pointer into OpenBao; `key_last4` is four characters of a tail (BCP-3821).
    """ # noqa: E501
    created_by_email: Optional[StrictStr] = None
    created_by_name: Optional[StrictStr] = None
    created_by_user_id: Optional[UUID] = None
    last_change_note: Optional[StrictStr] = Field(default=None, description="Optional free text explaining *why* the last change was made (\"Raised for the Q3 batch job\", \"Vendor deprecated the old endpoint\").  Admin-authored and rendered in the portal, so it is untrusted input: length-capped here, escaped on render.")
    last_modified_at: Optional[datetime] = Field(default=None, description="When the change named by `last_modified_by_*` happened.  Its own column rather than the row's `updated_at`, because `updated_at` is bumped by writes nobody is attributed for -- pairing the two would date a named admin's edit to a background job's clock. See the V75 migration for the full reasoning.")
    last_modified_by_email: Optional[StrictStr] = None
    last_modified_by_name: Optional[StrictStr] = None
    last_modified_by_user_id: Optional[UUID] = None
    auth_type: StrictStr
    base_url: StrictStr
    created_at: datetime
    id: UUID
    key_last4: Optional[StrictStr] = Field(default=None, description="Last four characters of the stored key, once known.  `None` means \"no tail to show\", which is three different situations — `stores_key_material` is what tells them apart. Populated whenever key material is written, and derived on first read for credentials that predate the column.")
    model_provider: StrictStr
    name: StrictStr
    org_id: UUID
    secret_path: StrictStr
    settings: Optional[Any]
    stores_key_material: StrictBool = Field(description="Whether this credential's auth type holds a secret at all. Derived from `auth_type`, not stored: it is a property of the auth type, so a column would be a second copy of the same fact, free to drift.")
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["created_by_email", "created_by_name", "created_by_user_id", "last_change_note", "last_modified_at", "last_modified_by_email", "last_modified_by_name", "last_modified_by_user_id", "auth_type", "base_url", "created_at", "id", "key_last4", "model_provider", "name", "org_id", "secret_path", "settings", "stores_key_material", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Connection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created_by_email (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_email is None and "created_by_email" in self.model_fields_set:
            _dict['created_by_email'] = None

        # set to None if created_by_name (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_name is None and "created_by_name" in self.model_fields_set:
            _dict['created_by_name'] = None

        # set to None if created_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_user_id is None and "created_by_user_id" in self.model_fields_set:
            _dict['created_by_user_id'] = None

        # set to None if last_change_note (nullable) is None
        # and model_fields_set contains the field
        if self.last_change_note is None and "last_change_note" in self.model_fields_set:
            _dict['last_change_note'] = None

        # set to None if last_modified_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_at is None and "last_modified_at" in self.model_fields_set:
            _dict['last_modified_at'] = None

        # set to None if last_modified_by_email (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by_email is None and "last_modified_by_email" in self.model_fields_set:
            _dict['last_modified_by_email'] = None

        # set to None if last_modified_by_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by_name is None and "last_modified_by_name" in self.model_fields_set:
            _dict['last_modified_by_name'] = None

        # set to None if last_modified_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by_user_id is None and "last_modified_by_user_id" in self.model_fields_set:
            _dict['last_modified_by_user_id'] = None

        # set to None if key_last4 (nullable) is None
        # and model_fields_set contains the field
        if self.key_last4 is None and "key_last4" in self.model_fields_set:
            _dict['key_last4'] = None

        # set to None if settings (nullable) is None
        # and model_fields_set contains the field
        if self.settings is None and "settings" in self.model_fields_set:
            _dict['settings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Connection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_by_email": obj.get("created_by_email"),
            "created_by_name": obj.get("created_by_name"),
            "created_by_user_id": obj.get("created_by_user_id"),
            "last_change_note": obj.get("last_change_note"),
            "last_modified_at": obj.get("last_modified_at"),
            "last_modified_by_email": obj.get("last_modified_by_email"),
            "last_modified_by_name": obj.get("last_modified_by_name"),
            "last_modified_by_user_id": obj.get("last_modified_by_user_id"),
            "auth_type": obj.get("auth_type"),
            "base_url": obj.get("base_url"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "key_last4": obj.get("key_last4"),
            "model_provider": obj.get("model_provider"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "secret_path": obj.get("secret_path"),
            "settings": obj.get("settings"),
            "stores_key_material": obj.get("stores_key_material"),
            "updated_at": obj.get("updated_at")
        })
        return _obj
