# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.billing_mode import BillingMode
from barndoor.models.billing_reason import BillingReason
from barndoor.models.model_sync_mode import ModelSyncMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateProviderRequest(BaseModel):
    """
    CreateProviderRequest
    """ # noqa: E501
    api_key: Optional[StrictStr] = Field(default=None, description="The provider's upstream API key. Required when `connection_id` is not supplied.")
    auth_type: Optional[StrictStr] = None
    base_url: StrictStr
    billing_mode: Optional[BillingMode] = Field(default=None, description="Whether the gateway records a per-token cost (BCP-3876). Omitted means `per_token` — a provider never stops recording cost by default, and nothing is inferred server-side. The create form *suggests* from the catalog entry and the auth type; `openrouter` is why inference would be wrong (it ships `pricing: []` and is API-billed).")
    billing_note: Optional[StrictStr] = Field(default=None, description="Optional free-text context for the arrangement, max [`BILLING_NOTE_MAX_LEN`] chars.")
    billing_reason: Optional[BillingReason] = Field(default=None, description="How the vendor bills. Required when `billing_mode` is `not_metered`, optional otherwise — see `validate_billing_fields`.")
    catalog_id: Optional[UUID] = Field(default=None, description="Optional reference to a provider_catalog entry.")
    change_note: Optional[StrictStr] = Field(default=None, description="Optional free-text note explaining why this provider was added (BCP-3998). Distinct from `billing_note`, which describes the *billing arrangement* and persists; this describes one change and is replaced by the next edit's note.")
    connection_id: Optional[UUID] = Field(default=None, description="Optional reference to a connection for shared credentials.")
    credentials: Optional[Any] = Field(default=None, description="Structured provider credentials. Preferred over `api_key` for provider-specific auth schemas; never returned by any API.")
    enforce_health_check: Optional[StrictBool] = Field(default=None, description="Whether routing should gate on the connectivity health check. `None`/omitted defaults to `true` (enforce). Set `false` to override the gate and serve the provider even when its probe fails.")
    model_provider: StrictStr
    model_sync_mode: Optional[ModelSyncMode] = Field(default=None, description="Whether this provider tracks Barndoor's model catalog (BCP-3811). Omitted means `off` — a provider is never enrolled by default.")
    models: Optional[List[StrictStr]] = Field(default=None, description="Upstream models to auto-create as 1:1 model mappings (alias = upstream name).")
    name: StrictStr
    request_timeout_secs: Optional[StrictInt] = Field(default=None, description="Provider-tier total-request timeout override (non-streaming). Operator-only and `None` by default: the effective value is written at the route tier (`model_mappings`), so this applies only if a route row leaves it unset, and then to every such route served by this provider. The range is fixed platform policy (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`); see [`crate::proxy::timeouts`].")
    settings: Optional[Any] = None
    stream_idle_timeout_secs: Optional[StrictInt] = Field(default=None, description="Provider-tier stream-idle timeout override (streaming). Operator-only and `None` by default; the effective value is written at the route tier (`model_mappings`). The range is fixed platform policy (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`); see [`crate::proxy::timeouts`].")
    __properties: ClassVar[List[str]] = ["api_key", "auth_type", "base_url", "billing_mode", "billing_note", "billing_reason", "catalog_id", "change_note", "connection_id", "credentials", "enforce_health_check", "model_provider", "model_sync_mode", "models", "name", "request_timeout_secs", "settings", "stream_idle_timeout_secs"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateProviderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if api_key (nullable) is None
        # and model_fields_set contains the field
        if self.api_key is None and "api_key" in self.model_fields_set:
            _dict['api_key'] = None

        # set to None if auth_type (nullable) is None
        # and model_fields_set contains the field
        if self.auth_type is None and "auth_type" in self.model_fields_set:
            _dict['auth_type'] = None

        # set to None if billing_mode (nullable) is None
        # and model_fields_set contains the field
        if self.billing_mode is None and "billing_mode" in self.model_fields_set:
            _dict['billing_mode'] = None

        # set to None if billing_note (nullable) is None
        # and model_fields_set contains the field
        if self.billing_note is None and "billing_note" in self.model_fields_set:
            _dict['billing_note'] = None

        # set to None if billing_reason (nullable) is None
        # and model_fields_set contains the field
        if self.billing_reason is None and "billing_reason" in self.model_fields_set:
            _dict['billing_reason'] = None

        # set to None if catalog_id (nullable) is None
        # and model_fields_set contains the field
        if self.catalog_id is None and "catalog_id" in self.model_fields_set:
            _dict['catalog_id'] = None

        # set to None if change_note (nullable) is None
        # and model_fields_set contains the field
        if self.change_note is None and "change_note" in self.model_fields_set:
            _dict['change_note'] = None

        # set to None if connection_id (nullable) is None
        # and model_fields_set contains the field
        if self.connection_id is None and "connection_id" in self.model_fields_set:
            _dict['connection_id'] = None

        # set to None if credentials (nullable) is None
        # and model_fields_set contains the field
        if self.credentials is None and "credentials" in self.model_fields_set:
            _dict['credentials'] = None

        # set to None if enforce_health_check (nullable) is None
        # and model_fields_set contains the field
        if self.enforce_health_check is None and "enforce_health_check" in self.model_fields_set:
            _dict['enforce_health_check'] = None

        # set to None if model_sync_mode (nullable) is None
        # and model_fields_set contains the field
        if self.model_sync_mode is None and "model_sync_mode" in self.model_fields_set:
            _dict['model_sync_mode'] = None

        # set to None if request_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.request_timeout_secs is None and "request_timeout_secs" in self.model_fields_set:
            _dict['request_timeout_secs'] = None

        # set to None if settings (nullable) is None
        # and model_fields_set contains the field
        if self.settings is None and "settings" in self.model_fields_set:
            _dict['settings'] = None

        # set to None if stream_idle_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.stream_idle_timeout_secs is None and "stream_idle_timeout_secs" in self.model_fields_set:
            _dict['stream_idle_timeout_secs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateProviderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key": obj.get("api_key"),
            "auth_type": obj.get("auth_type"),
            "base_url": obj.get("base_url"),
            "billing_mode": obj.get("billing_mode"),
            "billing_note": obj.get("billing_note"),
            "billing_reason": obj.get("billing_reason"),
            "catalog_id": obj.get("catalog_id"),
            "change_note": obj.get("change_note"),
            "connection_id": obj.get("connection_id"),
            "credentials": obj.get("credentials"),
            "enforce_health_check": obj.get("enforce_health_check"),
            "model_provider": obj.get("model_provider"),
            "model_sync_mode": obj.get("model_sync_mode"),
            "models": obj.get("models"),
            "name": obj.get("name"),
            "request_timeout_secs": obj.get("request_timeout_secs"),
            "settings": obj.get("settings"),
            "stream_idle_timeout_secs": obj.get("stream_idle_timeout_secs")
        })
        return _obj


