# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.model_source import ModelSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateModelMappingRequest(BaseModel):
    """
    CreateModelMappingRequest
    """ # noqa: E501
    bare_alias: Optional[StrictBool] = Field(default=None, description="Whether this row should participate in bare-name resolution. The admin handler treats `None` as \"infer from alias shape\" — custom aliases imply `true`, 1:1 enablement rows imply `false`. Pass `Some(true)` explicitly from the Model Routes tab to opt a 1:1 row into bare resolution.")
    change_note: Optional[StrictStr] = Field(default=None, description="Optional free-text note explaining why this route was added (BCP-3998). Surfaced on the row and mirrored into the audit event.")
    enabled: Optional[StrictBool] = None
    model_alias: StrictStr
    priority: Optional[StrictInt] = None
    provider_id: UUID
    request_timeout_secs: Optional[StrictInt] = Field(default=None, description="Per-mapping total-request timeout for non-streaming responses (streaming responses have no total timeout). On a custom-alias row this sets the *route* tier; on a 1:1 enablement (anchor) row it sets the *model* tier consulted for every alias of that model. `None` (the default) lets `model_mappings.create` write the platform default (`TOTAL_REQUEST_TIMEOUT_DEFAULT_SECS`) at the route tier. The range is fixed platform policy (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`); see [`crate::proxy::timeouts`].")
    retry_on_429_count: Optional[StrictInt] = Field(default=None, description="Same-route retries on upstream 429. 0 means immediate failover.")
    retry_on_429_max_wait_secs: Optional[StrictInt] = Field(default=None, description="Cap on honoring upstream `Retry-After`. 0 means use a small default.")
    source: Optional[ModelSource] = Field(default=None, description="Where this model came from. The Add Models dialog sends `Custom` from its free-text branch and `Catalog` from the picker; those two paths already differ client-side, and this is what carries the difference through to storage.  `None` means \"infer\": the handler inherits the anchor's provenance when one exists (so a route created on Model Routes agrees with the enablement it points at), and otherwise falls back to `Catalog`. SDK and curl callers therefore land on `Catalog` by default — accepted, since the pill exists to catch a typo in the UI and an API caller is not its audience.")
    stream_idle_timeout_secs: Optional[StrictInt] = Field(default=None, description="Per-mapping stream-idle (per-chunk) timeout for streaming responses. `None` (the default) lets `model_mappings.create` write the platform default (`STREAM_IDLE_TIMEOUT_DEFAULT_SECS`) at the route tier. The range is fixed platform policy (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`); see [`crate::proxy::timeouts`].")
    upstream_model: StrictStr
    __properties: ClassVar[List[str]] = ["bare_alias", "change_note", "enabled", "model_alias", "priority", "provider_id", "request_timeout_secs", "retry_on_429_count", "retry_on_429_max_wait_secs", "source", "stream_idle_timeout_secs", "upstream_model"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateModelMappingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bare_alias (nullable) is None
        # and model_fields_set contains the field
        if self.bare_alias is None and "bare_alias" in self.model_fields_set:
            _dict['bare_alias'] = None

        # set to None if change_note (nullable) is None
        # and model_fields_set contains the field
        if self.change_note is None and "change_note" in self.model_fields_set:
            _dict['change_note'] = None

        # set to None if request_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.request_timeout_secs is None and "request_timeout_secs" in self.model_fields_set:
            _dict['request_timeout_secs'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if stream_idle_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.stream_idle_timeout_secs is None and "stream_idle_timeout_secs" in self.model_fields_set:
            _dict['stream_idle_timeout_secs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateModelMappingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bare_alias": obj.get("bare_alias"),
            "change_note": obj.get("change_note"),
            "enabled": obj.get("enabled"),
            "model_alias": obj.get("model_alias"),
            "priority": obj.get("priority"),
            "provider_id": obj.get("provider_id"),
            "request_timeout_secs": obj.get("request_timeout_secs"),
            "retry_on_429_count": obj.get("retry_on_429_count"),
            "retry_on_429_max_wait_secs": obj.get("retry_on_429_max_wait_secs"),
            "source": obj.get("source"),
            "stream_idle_timeout_secs": obj.get("stream_idle_timeout_secs"),
            "upstream_model": obj.get("upstream_model")
        })
        return _obj


