# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.enforcement_policy_mcp_target_request import EnforcementPolicyMcpTargetRequest
from barndoor.models.enforcement_policy_principal_request import EnforcementPolicyPrincipalRequest
from barndoor.models.mask_format import MaskFormat
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateEnforcementPolicyRequest(BaseModel):
    """
    CreateEnforcementPolicyRequest
    """ # noqa: E501
    action: StrictStr
    detection_engine_ids: Optional[List[UUID]] = None
    dry_run: Optional[StrictBool] = None
    mask_format: Optional[MaskFormat] = Field(default=None, description="Partial-redaction shape; only valid with `POLICY_ACTION_MASK`.")
    mcp_targets: Optional[List[EnforcementPolicyMcpTargetRequest]] = None
    model_alias: Optional[StrictStr] = None
    name: StrictStr
    principals: Optional[List[EnforcementPolicyPrincipalRequest]] = None
    priority: Optional[StrictInt] = None
    provider_ids: Optional[List[StrictStr]] = None
    runtime_stage: Optional[StrictStr] = None
    target_kind: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["action", "detection_engine_ids", "dry_run", "mask_format", "mcp_targets", "model_alias", "name", "principals", "priority", "provider_ids", "runtime_stage", "target_kind"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateEnforcementPolicyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mask_format
        if self.mask_format:
            _dict['mask_format'] = self.mask_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in mcp_targets (list)
        _items = []
        if self.mcp_targets:
            for _item_mcp_targets in self.mcp_targets:
                _items.append(_item_mcp_targets.to_dict() if _item_mcp_targets is not None else None)
            _dict['mcp_targets'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in principals (list)
        _items = []
        if self.principals:
            for _item_principals in self.principals:
                _items.append(_item_principals.to_dict() if _item_principals is not None else None)
            _dict['principals'] = _items
        # set to None if mask_format (nullable) is None
        # and model_fields_set contains the field
        if self.mask_format is None and "mask_format" in self.model_fields_set:
            _dict['mask_format'] = None

        # set to None if model_alias (nullable) is None
        # and model_fields_set contains the field
        if self.model_alias is None and "model_alias" in self.model_fields_set:
            _dict['model_alias'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if runtime_stage (nullable) is None
        # and model_fields_set contains the field
        if self.runtime_stage is None and "runtime_stage" in self.model_fields_set:
            _dict['runtime_stage'] = None

        # set to None if target_kind (nullable) is None
        # and model_fields_set contains the field
        if self.target_kind is None and "target_kind" in self.model_fields_set:
            _dict['target_kind'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateEnforcementPolicyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "detection_engine_ids": obj.get("detection_engine_ids"),
            "dry_run": obj.get("dry_run"),
            "mask_format": MaskFormat.from_dict(obj["mask_format"]) if obj.get("mask_format") is not None else None,
            "mcp_targets": [EnforcementPolicyMcpTargetRequest.from_dict(_item) for _item in obj["mcp_targets"]] if obj.get("mcp_targets") is not None else None,
            "model_alias": obj.get("model_alias"),
            "name": obj.get("name"),
            "principals": [EnforcementPolicyPrincipalRequest.from_dict(_item) for _item in obj["principals"]] if obj.get("principals") is not None else None,
            "priority": obj.get("priority"),
            "provider_ids": obj.get("provider_ids"),
            "runtime_stage": obj.get("runtime_stage"),
            "target_kind": obj.get("target_kind")
        })
        return _obj


