# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from barndoor.models.long_context_tier_entry import LongContextTierEntry
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DefaultPricingEntry(BaseModel):
    """
    DefaultPricingEntry
    """ # noqa: E501
    cache_read_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Seeded prompt-cache rates from the provider YAML. `None` when the provider/model doesn't support caching (embeddings, vision, classic text-completion, etc.) — the admin UI hides the cache row entirely for those rather than rendering \"$0.00\", which would be a misleading override intent.")
    cache_write_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = None
    currency: StrictStr
    id: UUID
    input_cost_per_million_tokens: Union[StrictFloat, StrictInt]
    long_context: Optional[LongContextTierEntry] = Field(default=None, description="Seeded long-context surcharge tier (BCP-3904). `None` for the vast majority of models, which price at one rate at any prompt size.  Surfaced on the Import Defaults list so an admin can see that a default carries a second rate set *before* importing it — a listing that showed only the short-context rate would understate what the row is about to cost them.")
    model_name: StrictStr
    model_pattern: StrictStr
    output_cost_per_million_tokens: Union[StrictFloat, StrictInt]
    provider_slug: StrictStr
    source: StrictStr
    __properties: ClassVar[List[str]] = ["cache_read_cost_per_million_tokens", "cache_write_cost_per_million_tokens", "currency", "id", "input_cost_per_million_tokens", "long_context", "model_name", "model_pattern", "output_cost_per_million_tokens", "provider_slug", "source"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefaultPricingEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of long_context
        if self.long_context:
            _dict['long_context'] = self.long_context.to_dict()
        # set to None if cache_read_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_read_cost_per_million_tokens is None and "cache_read_cost_per_million_tokens" in self.model_fields_set:
            _dict['cache_read_cost_per_million_tokens'] = None

        # set to None if cache_write_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_write_cost_per_million_tokens is None and "cache_write_cost_per_million_tokens" in self.model_fields_set:
            _dict['cache_write_cost_per_million_tokens'] = None

        # set to None if long_context (nullable) is None
        # and model_fields_set contains the field
        if self.long_context is None and "long_context" in self.model_fields_set:
            _dict['long_context'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefaultPricingEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache_read_cost_per_million_tokens": obj.get("cache_read_cost_per_million_tokens"),
            "cache_write_cost_per_million_tokens": obj.get("cache_write_cost_per_million_tokens"),
            "currency": obj.get("currency"),
            "id": obj.get("id"),
            "input_cost_per_million_tokens": obj.get("input_cost_per_million_tokens"),
            "long_context": LongContextTierEntry.from_dict(obj["long_context"]) if obj.get("long_context") is not None else None,
            "model_name": obj.get("model_name"),
            "model_pattern": obj.get("model_pattern"),
            "output_cost_per_million_tokens": obj.get("output_cost_per_million_tokens"),
            "provider_slug": obj.get("provider_slug"),
            "source": obj.get("source")
        })
        return _obj


