# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DetectionTypeInfoResponse(BaseModel):
    """
    DetectionTypeInfoResponse
    """ # noqa: E501
    default_confidence: StrictStr
    default_severity: StrictStr
    description: StrictStr
    detection_type: StrictStr
    group: StrictStr
    is_custom: StrictBool
    name: StrictStr
    partial_mask_eligible: StrictBool = Field(description="Whether a MASK policy's `mask_format` may keep part of this type's value readable (BCP-4310). Free-text types are never eligible.")
    __properties: ClassVar[List[str]] = ["default_confidence", "default_severity", "description", "detection_type", "group", "is_custom", "name", "partial_mask_eligible"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DetectionTypeInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DetectionTypeInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "default_confidence": obj.get("default_confidence"),
            "default_severity": obj.get("default_severity"),
            "description": obj.get("description"),
            "detection_type": obj.get("detection_type"),
            "group": obj.get("group"),
            "is_custom": obj.get("is_custom"),
            "name": obj.get("name"),
            "partial_mask_eligible": obj.get("partial_mask_eligible")
        })
        return _obj
