# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from barndoor.models.long_context_tier import LongContextTier
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EffectivePricing(BaseModel):
    """
    The rate a request against a given mapping would be billed at, plus which tier produced it.  `source` is always present. Every other field is `None` when `source == \"none\"` — meaning no rule and no Barndoor default covers this model, so requests succeed but record $0. The rates are deliberately nullable rather than zero-filled: a UI that renders `$0.00` for an unpriced model reads as \"this model is free\", which is exactly the wrong conclusion.  Clients distinguish four states:  * field absent entirely → backend predates this annotation * `source == \"none\"` → unpriced, bills at $0 because the rate is *unknown* * `source == \"not_metered\"` → bills at $0 *by decision* (BCP-3876): the   provider's `billing_mode` is `subscription`, so no rate is consulted.   Rates are `None` here too, but for the opposite reason, and the UI must   not lump it in with \"unpriced\" — that bucket is a misconfiguration it   nags about and offers to bulk-disable. * anything else → priced, `input`/`output` populated
    """ # noqa: E501
    cache_read_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Prompt-cache read rate. `None` on a *priced* row means the rule sets no explicit cache rate, and the calculator bills cached input at the base input rate — render it as an inherited default, never as free.")
    cache_write_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Prompt-cache write rate. Same `None` semantics as the read rate.")
    input_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = None
    long_context: Optional[LongContextTier] = Field(default=None, description="The long-context surcharge on the matched rule (BCP-3904), when it has one.  Present here for the same reason the rates are: an admin ordering route priorities on cost has to be able to see that a target's price doubles above a prompt-size threshold. Rendering only the short-context rate for a Grok or GPT-6 route would understate its cost on exactly the long-context traffic that makes the choice matter.")
    output_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = None
    pricing_rule_id: Optional[UUID] = Field(default=None, description="The `model_pricing` version row that matched, so the UI can link a displayed rate back to the rule that produced it. `None` when `source == \"none\"`.")
    source: StrictStr = Field(description="Which resolution tier matched: `org_instance`, `org_catalog`, `org_generic`, `barndoor_default`, or `none`. Mirrors [`PricingSource::as_str`] so the value matches what audit events already record for the same decision.")
    __properties: ClassVar[List[str]] = ["cache_read_cost_per_million_tokens", "cache_write_cost_per_million_tokens", "input_cost_per_million_tokens", "long_context", "output_cost_per_million_tokens", "pricing_rule_id", "source"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EffectivePricing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of long_context
        if self.long_context:
            _dict['long_context'] = self.long_context.to_dict()
        # set to None if cache_read_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_read_cost_per_million_tokens is None and "cache_read_cost_per_million_tokens" in self.model_fields_set:
            _dict['cache_read_cost_per_million_tokens'] = None

        # set to None if cache_write_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_write_cost_per_million_tokens is None and "cache_write_cost_per_million_tokens" in self.model_fields_set:
            _dict['cache_write_cost_per_million_tokens'] = None

        # set to None if input_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.input_cost_per_million_tokens is None and "input_cost_per_million_tokens" in self.model_fields_set:
            _dict['input_cost_per_million_tokens'] = None

        # set to None if long_context (nullable) is None
        # and model_fields_set contains the field
        if self.long_context is None and "long_context" in self.model_fields_set:
            _dict['long_context'] = None

        # set to None if output_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.output_cost_per_million_tokens is None and "output_cost_per_million_tokens" in self.model_fields_set:
            _dict['output_cost_per_million_tokens'] = None

        # set to None if pricing_rule_id (nullable) is None
        # and model_fields_set contains the field
        if self.pricing_rule_id is None and "pricing_rule_id" in self.model_fields_set:
            _dict['pricing_rule_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EffectivePricing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache_read_cost_per_million_tokens": obj.get("cache_read_cost_per_million_tokens"),
            "cache_write_cost_per_million_tokens": obj.get("cache_write_cost_per_million_tokens"),
            "input_cost_per_million_tokens": obj.get("input_cost_per_million_tokens"),
            "long_context": LongContextTier.from_dict(obj["long_context"]) if obj.get("long_context") is not None else None,
            "output_cost_per_million_tokens": obj.get("output_cost_per_million_tokens"),
            "pricing_rule_id": obj.get("pricing_rule_id"),
            "source": obj.get("source")
        })
        return _obj


