# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from barndoor.models.enforcement_policy_mcp_target_response import EnforcementPolicyMcpTargetResponse
from barndoor.models.enforcement_policy_principal_response import EnforcementPolicyPrincipalResponse
from barndoor.models.mask_format import MaskFormat
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EnforcementPolicyResponse(BaseModel):
    """
    EnforcementPolicyResponse
    """ # noqa: E501
    action: StrictStr
    created_at: StrictStr
    created_by: StrictStr
    detection_engine_ids: List[StrictStr]
    dry_run: StrictBool
    id: StrictStr
    mask_format: Optional[MaskFormat] = None
    mcp_targets: List[EnforcementPolicyMcpTargetResponse]
    model_alias: Optional[StrictStr] = None
    name: StrictStr
    org_id: StrictStr
    principals: List[EnforcementPolicyPrincipalResponse]
    priority: StrictInt
    provider_ids: List[StrictStr]
    runtime_stage: StrictStr
    target_kind: StrictStr
    updated_at: StrictStr
    updated_by: StrictStr
    __properties: ClassVar[List[str]] = ["action", "created_at", "created_by", "detection_engine_ids", "dry_run", "id", "mask_format", "mcp_targets", "model_alias", "name", "org_id", "principals", "priority", "provider_ids", "runtime_stage", "target_kind", "updated_at", "updated_by"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnforcementPolicyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mask_format
        if self.mask_format:
            _dict['mask_format'] = self.mask_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in mcp_targets (list)
        _items = []
        if self.mcp_targets:
            for _item_mcp_targets in self.mcp_targets:
                _items.append(_item_mcp_targets.to_dict() if _item_mcp_targets is not None else None)
            _dict['mcp_targets'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in principals (list)
        _items = []
        if self.principals:
            for _item_principals in self.principals:
                _items.append(_item_principals.to_dict() if _item_principals is not None else None)
            _dict['principals'] = _items
        # set to None if mask_format (nullable) is None
        # and model_fields_set contains the field
        if self.mask_format is None and "mask_format" in self.model_fields_set:
            _dict['mask_format'] = None

        # set to None if model_alias (nullable) is None
        # and model_fields_set contains the field
        if self.model_alias is None and "model_alias" in self.model_fields_set:
            _dict['model_alias'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnforcementPolicyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "detection_engine_ids": obj.get("detection_engine_ids"),
            "dry_run": obj.get("dry_run"),
            "id": obj.get("id"),
            "mask_format": MaskFormat.from_dict(obj["mask_format"]) if obj.get("mask_format") is not None else None,
            "mcp_targets": [EnforcementPolicyMcpTargetResponse.from_dict(_item) for _item in obj["mcp_targets"]] if obj.get("mcp_targets") is not None else None,
            "model_alias": obj.get("model_alias"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "principals": [EnforcementPolicyPrincipalResponse.from_dict(_item) for _item in obj["principals"]] if obj.get("principals") is not None else None,
            "priority": obj.get("priority"),
            "provider_ids": obj.get("provider_ids"),
            "runtime_stage": obj.get("runtime_stage"),
            "target_kind": obj.get("target_kind"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by")
        })
        return _obj
