# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ExportSettings(BaseModel):
    """
    ExportSettings
    """ # noqa: E501
    batch_size: StrictInt
    buffer_size: StrictInt
    flush_interval_seconds: StrictInt
    included_event_types: Optional[List[StrictStr]] = None
    max_retries: StrictInt
    retry_backoff_seconds: StrictInt
    __properties: ClassVar[List[str]] = ["batch_size", "buffer_size", "flush_interval_seconds", "included_event_types", "max_retries", "retry_backoff_seconds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExportSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if included_event_types (nullable) is None
        # and model_fields_set contains the field
        if self.included_event_types is None and "included_event_types" in self.model_fields_set:
            _dict['included_event_types'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExportSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "batch_size": obj.get("batch_size"),
            "buffer_size": obj.get("buffer_size"),
            "flush_interval_seconds": obj.get("flush_interval_seconds"),
            "included_event_types": obj.get("included_event_types"),
            "max_retries": obj.get("max_retries"),
            "retry_backoff_seconds": obj.get("retry_backoff_seconds")
        })
        return _obj


