# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IdpConnectionResponse(BaseModel):
    """
    Response containing current IdP connection configuration.
    """ # noqa: E501
    configured: Optional[StrictBool] = False
    alias: Optional[StrictStr] = None
    expected_alias: Optional[StrictStr] = None
    display_name: Optional[StrictStr] = None
    issuer: Optional[StrictStr] = None
    authorization_url: Optional[StrictStr] = None
    token_url: Optional[StrictStr] = None
    userinfo_url: Optional[StrictStr] = None
    jwks_url: Optional[StrictStr] = None
    logout_url: Optional[StrictStr] = None
    scopes: Optional[StrictStr] = None
    prompt: Optional[StrictStr] = ''
    client_id_configured: Optional[StrictBool] = False
    client_secret_configured: Optional[StrictBool] = False
    domain: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["configured", "alias", "expected_alias", "display_name", "issuer", "authorization_url", "token_url", "userinfo_url", "jwks_url", "logout_url", "scopes", "prompt", "client_id_configured", "client_secret_configured", "domain"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdpConnectionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if alias (nullable) is None
        # and model_fields_set contains the field
        if self.alias is None and "alias" in self.model_fields_set:
            _dict['alias'] = None

        # set to None if expected_alias (nullable) is None
        # and model_fields_set contains the field
        if self.expected_alias is None and "expected_alias" in self.model_fields_set:
            _dict['expected_alias'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if issuer (nullable) is None
        # and model_fields_set contains the field
        if self.issuer is None and "issuer" in self.model_fields_set:
            _dict['issuer'] = None

        # set to None if authorization_url (nullable) is None
        # and model_fields_set contains the field
        if self.authorization_url is None and "authorization_url" in self.model_fields_set:
            _dict['authorization_url'] = None

        # set to None if token_url (nullable) is None
        # and model_fields_set contains the field
        if self.token_url is None and "token_url" in self.model_fields_set:
            _dict['token_url'] = None

        # set to None if userinfo_url (nullable) is None
        # and model_fields_set contains the field
        if self.userinfo_url is None and "userinfo_url" in self.model_fields_set:
            _dict['userinfo_url'] = None

        # set to None if jwks_url (nullable) is None
        # and model_fields_set contains the field
        if self.jwks_url is None and "jwks_url" in self.model_fields_set:
            _dict['jwks_url'] = None

        # set to None if logout_url (nullable) is None
        # and model_fields_set contains the field
        if self.logout_url is None and "logout_url" in self.model_fields_set:
            _dict['logout_url'] = None

        # set to None if scopes (nullable) is None
        # and model_fields_set contains the field
        if self.scopes is None and "scopes" in self.model_fields_set:
            _dict['scopes'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdpConnectionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configured": obj.get("configured") if obj.get("configured") is not None else False,
            "alias": obj.get("alias"),
            "expected_alias": obj.get("expected_alias"),
            "display_name": obj.get("display_name"),
            "issuer": obj.get("issuer"),
            "authorization_url": obj.get("authorization_url"),
            "token_url": obj.get("token_url"),
            "userinfo_url": obj.get("userinfo_url"),
            "jwks_url": obj.get("jwks_url"),
            "logout_url": obj.get("logout_url"),
            "scopes": obj.get("scopes"),
            "prompt": obj.get("prompt") if obj.get("prompt") is not None else '',
            "client_id_configured": obj.get("client_id_configured") if obj.get("client_id_configured") is not None else False,
            "client_secret_configured": obj.get("client_secret_configured") if obj.get("client_secret_configured") is not None else False,
            "domain": obj.get("domain")
        })
        return _obj
