# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LlmGatewayAwsRoleConfigResponse(BaseModel):
    """
    Whether Barndoor's own AWS principal is configured for role-assumption trust policies.  Named with the service prefix because dlp-service publishes a type of the same shape under the unprefixed name, and the merged document has ONE global component namespace. The generator fails closed on two services defining the same referenced component differently, which is how this was caught. Making the two byte-identical instead would silently couple two services' schemas and turn any later divergence into a hard failure of the whole spec.
    """ # noqa: E501
    configured: StrictBool = Field(description="True when Barndoor has a principal ARN to put in a customer trust policy.")
    principal_arn: Optional[StrictStr] = Field(default=None, description="The ARN customers name as the trusted principal; null when unconfigured.")
    __properties: ClassVar[List[str]] = ["configured", "principal_arn"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LlmGatewayAwsRoleConfigResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if principal_arn (nullable) is None
        # and model_fields_set contains the field
        if self.principal_arn is None and "principal_arn" in self.model_fields_set:
            _dict['principal_arn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LlmGatewayAwsRoleConfigResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configured": obj.get("configured"),
            "principal_arn": obj.get("principal_arn")
        })
        return _obj
