# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from barndoor.models.mask_keep import MaskKeep
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MaskFormat(BaseModel):
    """
    The `mask_format` object stored on `dlp.enforcement_policies.mask_format` and carried on the admin REST surface. `deny_unknown_fields` so a typo in a client (or a future key an older server does not understand) fails loudly.
    """ # noqa: E501
    keep: MaskKeep
    keep_chars: Annotated[int, Field(strict=True, ge=0)]
    mask_char: Optional[StrictStr] = None
    preserve_separators: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["keep", "keep_chars", "mask_char", "preserve_separators"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MaskFormat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MaskFormat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "keep": obj.get("keep"),
            "keep_chars": obj.get("keep_chars"),
            "mask_char": obj.get("mask_char"),
            "preserve_separators": obj.get("preserve_separators")
        })
        return _obj


