# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.mcp_server_category import MCPServerCategory
from barndoor.models.protocol import Protocol
from barndoor.models.server_source import ServerSource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MCPServerDirectoryRead(BaseModel):
    """
    MCPServerDirectoryRead
    """ # noqa: E501
    id: UUID
    created_at: datetime
    updated_at: datetime
    name: StrictStr
    description: Optional[StrictStr]
    icon: Optional[StrictStr]
    slug: Optional[StrictStr]
    organization_id: Optional[UUID]
    url: StrictStr
    protocol: Protocol
    source: ServerSource
    provider: StrictStr = Field(description="The provider name to use when registering with OpenBao")
    provider_options: Optional[Any]
    scopes: List[StrictStr]
    oauth_metadata: Dict[str, Any]
    protected_resource_metadata: Dict[str, Any]
    allow_oauth_override: StrictBool
    meta: Optional[Dict[str, Any]]
    auth_params: Optional[Any]
    credential_schema: Optional[Any]
    public: StrictBool
    requires_auth: StrictBool
    requires_auth_observed_at: Optional[datetime]
    categories: List[MCPServerCategory]
    active_server_ids: Optional[List[StrictStr]]
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "name", "description", "icon", "slug", "organization_id", "url", "protocol", "source", "provider", "provider_options", "scopes", "oauth_metadata", "protected_resource_metadata", "allow_oauth_override", "meta", "auth_params", "credential_schema", "public", "requires_auth", "requires_auth_observed_at", "categories", "active_server_ids"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MCPServerDirectoryRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in categories (list)
        _items = []
        if self.categories:
            for _item_categories in self.categories:
                _items.append(_item_categories.to_dict() if _item_categories is not None else None)
            _dict['categories'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if icon (nullable) is None
        # and model_fields_set contains the field
        if self.icon is None and "icon" in self.model_fields_set:
            _dict['icon'] = None

        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organization_id'] = None

        # set to None if provider_options (nullable) is None
        # and model_fields_set contains the field
        if self.provider_options is None and "provider_options" in self.model_fields_set:
            _dict['provider_options'] = None

        # set to None if meta (nullable) is None
        # and model_fields_set contains the field
        if self.meta is None and "meta" in self.model_fields_set:
            _dict['meta'] = None

        # set to None if auth_params (nullable) is None
        # and model_fields_set contains the field
        if self.auth_params is None and "auth_params" in self.model_fields_set:
            _dict['auth_params'] = None

        # set to None if credential_schema (nullable) is None
        # and model_fields_set contains the field
        if self.credential_schema is None and "credential_schema" in self.model_fields_set:
            _dict['credential_schema'] = None

        # set to None if requires_auth_observed_at (nullable) is None
        # and model_fields_set contains the field
        if self.requires_auth_observed_at is None and "requires_auth_observed_at" in self.model_fields_set:
            _dict['requires_auth_observed_at'] = None

        # set to None if active_server_ids (nullable) is None
        # and model_fields_set contains the field
        if self.active_server_ids is None and "active_server_ids" in self.model_fields_set:
            _dict['active_server_ids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MCPServerDirectoryRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "icon": obj.get("icon"),
            "slug": obj.get("slug"),
            "organization_id": obj.get("organization_id"),
            "url": obj.get("url"),
            "protocol": obj.get("protocol"),
            "source": obj.get("source"),
            "provider": obj.get("provider") if obj.get("provider") is not None else 'custom',
            "provider_options": obj.get("provider_options"),
            "scopes": obj.get("scopes"),
            "oauth_metadata": obj.get("oauth_metadata"),
            "protected_resource_metadata": obj.get("protected_resource_metadata"),
            "allow_oauth_override": obj.get("allow_oauth_override") if obj.get("allow_oauth_override") is not None else False,
            "meta": obj.get("meta"),
            "auth_params": obj.get("auth_params"),
            "credential_schema": obj.get("credential_schema"),
            "public": obj.get("public") if obj.get("public") is not None else False,
            "requires_auth": obj.get("requires_auth") if obj.get("requires_auth") is not None else False,
            "requires_auth_observed_at": obj.get("requires_auth_observed_at"),
            "categories": [MCPServerCategory.from_dict(_item) for _item in obj["categories"]] if obj.get("categories") is not None else None,
            "active_server_ids": obj.get("active_server_ids")
        })
        return _obj


