# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelAccessTargetOneOf4(BaseModel):
    """
    Match every route in a named route group (BCP-3961) — the way an org says \"the Engineering team's routes\" once instead of listing aliases and re-editing the policy whenever a route is added.  **This variant never reaches [`ModelAccessTarget::matches`].** [`ModelAccessPolicyDb::get_enabled_by_org`] — the only load path governance uses — expands it into one [`ModelAccessTarget::ModelAlias`] per member alias, so the request path stays a pure function over [`MatchContext`] with no database access. `matches`/`grants` still answer `false` for it as a fail-safe: if some future load path forgets to expand, a group target denies nothing and grants nothing rather than matching everything.  `list_by_org` (the admin path) deliberately does *not* expand, so the policy editor shows \"Engineering\" rather than its fourteen members.
    """ # noqa: E501
    group_id: UUID
    kind: StrictStr
    __properties: ClassVar[List[str]] = ["group_id", "kind"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['route_group']):
            raise ValueError("must be one of enum values ('route_group')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelAccessTargetOneOf4 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelAccessTargetOneOf4 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "group_id": obj.get("group_id"),
            "kind": obj.get("kind")
        })
        return _obj


