# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelSource(str, Enum):
    """
    Where a `model_mappings` row came from. Persisted as a `VARCHAR(16)` constrained to `catalog | custom` (see migration V61).  This records *intent at create time* — whether an admin picked the model out of the provider catalog or typed a name into the \"Custom Model\" box — and deliberately never changes afterwards. It is not a claim about whether the catalog still lists the model today: that is live state, drifts as vendors retire models, and belongs to BCP-3038's stale-route detection. Keeping the two apart is what lets a retired-from-catalog model avoid rendering as a deliberate custom choice. See migration V61 for the full rationale.
    """

    """
    allowed enum values
    """
    CATALOG = 'catalog'
    CUSTOM = 'custom'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelSource from a JSON string"""
        return cls(json.loads(json_str))


