# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from barndoor.models.model_access_target_one_of import ModelAccessTargetOneOf
from barndoor.models.model_access_target_one_of1 import ModelAccessTargetOneOf1
from barndoor.models.model_access_target_one_of2 import ModelAccessTargetOneOf2
from barndoor.models.model_access_target_one_of3 import ModelAccessTargetOneOf3
from barndoor.models.model_access_target_one_of4 import ModelAccessTargetOneOf4
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

MODELACCESSTARGET_ONE_OF_SCHEMAS = ["ModelAccessTargetOneOf", "ModelAccessTargetOneOf1", "ModelAccessTargetOneOf2", "ModelAccessTargetOneOf3", "ModelAccessTargetOneOf4"]

class ModelAccessTarget(BaseModel):
    """
    A single restriction target inside a [`ModelAccessPolicy`].  Targets answer the question \"*what* is being allowed/denied?\" — distinct from `scope_type`, which answers \"*who* is the policy applied to?\". A policy's `targets` list is OR-ed when matching: a request matches the policy if any one of its targets matches the (provider, model) pair.  Serialised to JSONB with a `kind` discriminator so it round-trips cleanly through the admin REST API.  `ModelAlias` matches against the literal `model` field in the request. `Model` matches against the *resolved upstream model* — i.e. the underlying model the routed mapping points at. The two are distinct because the admin UI lets admins pick along either dimension: a `goto` alias fanned out across providers is best expressed with `ModelAlias`, while \"block any request that ends up at gpt-4o-mini regardless of the alias used\" is best expressed with `Model` (so it fires even when `goto` resolves to `gpt-4o-mini`).
    """
    # data type: ModelAccessTargetOneOf
    oneof_schema_1_validator: Optional[ModelAccessTargetOneOf] = None
    # data type: ModelAccessTargetOneOf1
    oneof_schema_2_validator: Optional[ModelAccessTargetOneOf1] = None
    # data type: ModelAccessTargetOneOf2
    oneof_schema_3_validator: Optional[ModelAccessTargetOneOf2] = None
    # data type: ModelAccessTargetOneOf3
    oneof_schema_4_validator: Optional[ModelAccessTargetOneOf3] = None
    # data type: ModelAccessTargetOneOf4
    oneof_schema_5_validator: Optional[ModelAccessTargetOneOf4] = None
    actual_instance: Optional[Union[ModelAccessTargetOneOf, ModelAccessTargetOneOf1, ModelAccessTargetOneOf2, ModelAccessTargetOneOf3, ModelAccessTargetOneOf4]] = None
    one_of_schemas: Set[str] = { "ModelAccessTargetOneOf", "ModelAccessTargetOneOf1", "ModelAccessTargetOneOf2", "ModelAccessTargetOneOf3", "ModelAccessTargetOneOf4" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ModelAccessTarget.model_construct()
        error_messages = []
        match = 0
        # validate data type: ModelAccessTargetOneOf
        if not isinstance(v, ModelAccessTargetOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelAccessTargetOneOf`")
        else:
            match += 1
        # validate data type: ModelAccessTargetOneOf1
        if not isinstance(v, ModelAccessTargetOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelAccessTargetOneOf1`")
        else:
            match += 1
        # validate data type: ModelAccessTargetOneOf2
        if not isinstance(v, ModelAccessTargetOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelAccessTargetOneOf2`")
        else:
            match += 1
        # validate data type: ModelAccessTargetOneOf3
        if not isinstance(v, ModelAccessTargetOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelAccessTargetOneOf3`")
        else:
            match += 1
        # validate data type: ModelAccessTargetOneOf4
        if not isinstance(v, ModelAccessTargetOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModelAccessTargetOneOf4`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ModelAccessTarget with oneOf schemas: ModelAccessTargetOneOf, ModelAccessTargetOneOf1, ModelAccessTargetOneOf2, ModelAccessTargetOneOf3, ModelAccessTargetOneOf4. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ModelAccessTarget with oneOf schemas: ModelAccessTargetOneOf, ModelAccessTargetOneOf1, ModelAccessTargetOneOf2, ModelAccessTargetOneOf3, ModelAccessTargetOneOf4. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ModelAccessTargetOneOf
        try:
            instance.actual_instance = ModelAccessTargetOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ModelAccessTargetOneOf1
        try:
            instance.actual_instance = ModelAccessTargetOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ModelAccessTargetOneOf2
        try:
            instance.actual_instance = ModelAccessTargetOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ModelAccessTargetOneOf3
        try:
            instance.actual_instance = ModelAccessTargetOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ModelAccessTargetOneOf4
        try:
            instance.actual_instance = ModelAccessTargetOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ModelAccessTarget with oneOf schemas: ModelAccessTargetOneOf, ModelAccessTargetOneOf1, ModelAccessTargetOneOf2, ModelAccessTargetOneOf3, ModelAccessTargetOneOf4. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ModelAccessTarget with oneOf schemas: ModelAccessTargetOneOf, ModelAccessTargetOneOf1, ModelAccessTargetOneOf2, ModelAccessTargetOneOf3, ModelAccessTargetOneOf4. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ModelAccessTargetOneOf, ModelAccessTargetOneOf1, ModelAccessTargetOneOf2, ModelAccessTargetOneOf3, ModelAccessTargetOneOf4]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
