# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from barndoor.models.expression import Expression
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

OFINNER1_ONE_OF_SCHEMAS = ["Expression", "OperatorAllOutput", "OperatorAnyOutput", "OperatorNoneOutput"]

class OfInner1(BaseModel):
    """
    OfInner1
    """
    # data type: Expression
    oneof_schema_1_validator: Optional[Expression] = None
    # data type: OperatorAllOutput
    oneof_schema_2_validator: Optional[OperatorAllOutput] = None
    # data type: OperatorAnyOutput
    oneof_schema_3_validator: Optional[OperatorAnyOutput] = None
    # data type: OperatorNoneOutput
    oneof_schema_4_validator: Optional[OperatorNoneOutput] = None
    actual_instance: Optional[Union[Expression, OperatorAllOutput, OperatorAnyOutput, OperatorNoneOutput]] = None
    one_of_schemas: Set[str] = { "Expression", "OperatorAllOutput", "OperatorAnyOutput", "OperatorNoneOutput" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = OfInner1.model_construct()
        error_messages = []
        match = 0
        # validate data type: Expression
        if not isinstance(v, Expression):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Expression`")
        else:
            match += 1
        # validate data type: OperatorAllOutput
        if not isinstance(v, OperatorAllOutput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OperatorAllOutput`")
        else:
            match += 1
        # validate data type: OperatorAnyOutput
        if not isinstance(v, OperatorAnyOutput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OperatorAnyOutput`")
        else:
            match += 1
        # validate data type: OperatorNoneOutput
        if not isinstance(v, OperatorNoneOutput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OperatorNoneOutput`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OfInner1 with oneOf schemas: Expression, OperatorAllOutput, OperatorAnyOutput, OperatorNoneOutput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OfInner1 with oneOf schemas: Expression, OperatorAllOutput, OperatorAnyOutput, OperatorNoneOutput. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Expression
        try:
            instance.actual_instance = Expression.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OperatorAllOutput
        try:
            instance.actual_instance = OperatorAllOutput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OperatorAnyOutput
        try:
            instance.actual_instance = OperatorAnyOutput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OperatorNoneOutput
        try:
            instance.actual_instance = OperatorNoneOutput.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into OfInner1 with oneOf schemas: Expression, OperatorAllOutput, OperatorAnyOutput, OperatorNoneOutput. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OfInner1 with oneOf schemas: Expression, OperatorAllOutput, OperatorAnyOutput, OperatorNoneOutput. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Expression, OperatorAllOutput, OperatorAnyOutput, OperatorNoneOutput]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from barndoor.models.operator_all_output import OperatorAllOutput
from barndoor.models.operator_any_output import OperatorAnyOutput
from barndoor.models.operator_none_output import OperatorNoneOutput
# TODO: Rewrite to not use raise_errors
OfInner1.model_rebuild(raise_errors=False)

