# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PolicyImpactSummary(BaseModel):
    """
    One ``policy.policy_impact`` row, as returned by the impact list/detail routes.  Built with ``model_validate(row, from_attributes=True)`` directly off the ORM row — the field set below is a straight projection of ``policy_service.db.policy_impact.PolicyImpact``, so there is no hand-mapping to drift out of sync.
    """ # noqa: E501
    id: UUID
    policy_id: UUID
    mcp_server_id: StrictStr
    change_kind: StrictStr
    tool_name: StrictStr
    severity: StrictStr
    status: StrictStr
    from_version: Optional[StrictInt] = None
    to_version: StrictInt
    snapshot_id: UUID
    policy_status_at_eval: StrictStr
    detail: Optional[Dict[str, Any]] = None
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[StrictStr] = None
    resolved_at: Optional[datetime] = None
    resolved_by: Optional[StrictStr] = None
    resolution: Optional[StrictStr] = None
    created_at: datetime
    __properties: ClassVar[List[str]] = ["id", "policy_id", "mcp_server_id", "change_kind", "tool_name", "severity", "status", "from_version", "to_version", "snapshot_id", "policy_status_at_eval", "detail", "acknowledged_at", "acknowledged_by", "resolved_at", "resolved_by", "resolution", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicyImpactSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if from_version (nullable) is None
        # and model_fields_set contains the field
        if self.from_version is None and "from_version" in self.model_fields_set:
            _dict['from_version'] = None

        # set to None if acknowledged_at (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_at is None and "acknowledged_at" in self.model_fields_set:
            _dict['acknowledged_at'] = None

        # set to None if acknowledged_by (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_by is None and "acknowledged_by" in self.model_fields_set:
            _dict['acknowledged_by'] = None

        # set to None if resolved_at (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_at is None and "resolved_at" in self.model_fields_set:
            _dict['resolved_at'] = None

        # set to None if resolved_by (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_by is None and "resolved_by" in self.model_fields_set:
            _dict['resolved_by'] = None

        # set to None if resolution (nullable) is None
        # and model_fields_set contains the field
        if self.resolution is None and "resolution" in self.model_fields_set:
            _dict['resolution'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicyImpactSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "policy_id": obj.get("policy_id"),
            "mcp_server_id": obj.get("mcp_server_id"),
            "change_kind": obj.get("change_kind"),
            "tool_name": obj.get("tool_name"),
            "severity": obj.get("severity"),
            "status": obj.get("status"),
            "from_version": obj.get("from_version"),
            "to_version": obj.get("to_version"),
            "snapshot_id": obj.get("snapshot_id"),
            "policy_status_at_eval": obj.get("policy_status_at_eval"),
            "detail": obj.get("detail"),
            "acknowledged_at": obj.get("acknowledged_at"),
            "acknowledged_by": obj.get("acknowledged_by"),
            "resolved_at": obj.get("resolved_at"),
            "resolved_by": obj.get("resolved_by"),
            "resolution": obj.get("resolution"),
            "created_at": obj.get("created_at")
        })
        return _obj


