# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PolicyStatus(str, Enum):
    """
    Policy lifecycle status.  - ``DRAFT``: authored but never enforced. Safe to build up incrementally. - ``ACTIVE``: enforcing on live tool calls. - ``INACTIVE``: previously active, now suspended. Rules are retained but not enforced. - ``ARCHIVED``: retired. Kept for audit history; not enforced and not offered for reuse.  A newly created policy defaults to ``DRAFT``; set ``ACTIVE`` explicitly to begin enforcing.
    """

    """
    allowed enum values
    """
    DRAFT = 'DRAFT'
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    ARCHIVED = 'ARCHIVED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PolicyStatus from a JSON string"""
        return cls(json.loads(json_str))


