# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.billing_mode import BillingMode
from barndoor.models.billing_reason import BillingReason
from barndoor.models.model_sync_mode import ModelSyncMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Provider(BaseModel):
    """
    Provider
    """ # noqa: E501
    created_by_email: Optional[StrictStr] = None
    created_by_name: Optional[StrictStr] = None
    created_by_user_id: Optional[UUID] = None
    last_change_note: Optional[StrictStr] = Field(default=None, description="Optional free text explaining *why* the last change was made (\"Raised for the Q3 batch job\", \"Vendor deprecated the old endpoint\").  Admin-authored and rendered in the portal, so it is untrusted input: length-capped here, escaped on render.")
    last_modified_at: Optional[datetime] = Field(default=None, description="When the change named by `last_modified_by_*` happened.  Its own column rather than the row's `updated_at`, because `updated_at` is bumped by writes nobody is attributed for -- pairing the two would date a named admin's edit to a background job's clock. See the V75 migration for the full reasoning.")
    last_modified_by_email: Optional[StrictStr] = None
    last_modified_by_name: Optional[StrictStr] = None
    last_modified_by_user_id: Optional[UUID] = None
    auth_type: StrictStr
    base_url: StrictStr
    billing_mode: BillingMode = Field(description="Whether the gateway records a per-token cost for this provider's traffic (V69 / BCP-3876). `PerToken` for every provider that has not opted in, which is the default and the back-compat value.  The request path does **not** read this field: billing consults [`ai_governance::CostCalculator`]'s own cached not-metered set, which is refreshed from the same query as pricing. This exists for the admin API surface and the audit trail.")
    billing_note: Optional[StrictStr] = Field(default=None, description="Optional free-text context for the arrangement (max 200 chars). Human-readable only — never parsed, never aggregated.")
    billing_reason: Optional[BillingReason] = Field(default=None, description="How the vendor bills this provider. Required when `billing_mode` is `NotMetered`, optional otherwise (V69 CHECK-enforced) — a subscription billing overages is both per-token and a subscription. Purely descriptive: no code branches on it, which is what lets a new reason be added without touching the billing path.")
    catalog_id: Optional[UUID] = None
    catalog_slug: Optional[StrictStr] = None
    connection_id: Optional[UUID] = None
    created_at: datetime
    enabled: StrictBool
    enforce_health_check: StrictBool = Field(description="Operator override for the health gate (V46). When `true` (default) routing requires `health_status <> 'unhealthy'`; when `false` the gate is bypassed and the provider serves regardless of probe results (we still probe and surface health). Lets an admin force traffic through a false-positive probe.")
    health_checked_at: Optional[datetime] = Field(default=None, description="When the last connectivity probe ran (NULL until the first probe).")
    health_detail: Optional[StrictStr] = Field(default=None, description="Human-readable reason for the last `unhealthy` probe (NULL otherwise).")
    health_status: StrictStr = Field(description="Observed upstream reachability, recorded separately from `enabled` (operator intent) so the system never overwrites the toggle (V45). One of `unverified` | `healthy` | `unhealthy`. `unverified` is the back-compat default and also covers provider families we don't probe (Bedrock/Vertex/Azure, claude_oauth, codex_oauth). A provider serves traffic only when `enabled` AND `health_status <> 'unhealthy'`: a failed probe auto-suspends it from routing (see `resolve_*`) without disabling it, and it resumes once a probe records it healthy again.")
    id: UUID
    model_provider: StrictStr
    model_sync_mode: ModelSyncMode = Field(description="Whether this provider tracks Barndoor's model catalog, and how far (V63 / BCP-3811). `Off` for every provider that has not opted in, which is the default and the back-compat value.")
    name: StrictStr
    org_id: UUID
    request_timeout_secs: Optional[StrictInt] = Field(default=None, description="Provider-tier total-request timeout override (non-streaming). Operator-only and `None` by default: the effective value is written at the route tier (`model_mappings`), so this only applies if a route row somehow leaves it unset. Range `TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS` is enforced by the CHECK constraint (see `proxy::timeouts`).")
    secret_path: StrictStr
    settings: Optional[Any]
    stream_idle_timeout_secs: Optional[StrictInt] = Field(default=None, description="Provider-tier stream-idle timeout override (streaming). Operator-only and `None` by default; the effective value is written at the route tier (`model_mappings`). Range `STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS` is enforced by the CHECK constraint (see `proxy::timeouts`).")
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["created_by_email", "created_by_name", "created_by_user_id", "last_change_note", "last_modified_at", "last_modified_by_email", "last_modified_by_name", "last_modified_by_user_id", "auth_type", "base_url", "billing_mode", "billing_note", "billing_reason", "catalog_id", "catalog_slug", "connection_id", "created_at", "enabled", "enforce_health_check", "health_checked_at", "health_detail", "health_status", "id", "model_provider", "model_sync_mode", "name", "org_id", "request_timeout_secs", "secret_path", "settings", "stream_idle_timeout_secs", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Provider from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created_by_email (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_email is None and "created_by_email" in self.model_fields_set:
            _dict['created_by_email'] = None

        # set to None if created_by_name (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_name is None and "created_by_name" in self.model_fields_set:
            _dict['created_by_name'] = None

        # set to None if created_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_user_id is None and "created_by_user_id" in self.model_fields_set:
            _dict['created_by_user_id'] = None

        # set to None if last_change_note (nullable) is None
        # and model_fields_set contains the field
        if self.last_change_note is None and "last_change_note" in self.model_fields_set:
            _dict['last_change_note'] = None

        # set to None if last_modified_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_at is None and "last_modified_at" in self.model_fields_set:
            _dict['last_modified_at'] = None

        # set to None if last_modified_by_email (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by_email is None and "last_modified_by_email" in self.model_fields_set:
            _dict['last_modified_by_email'] = None

        # set to None if last_modified_by_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by_name is None and "last_modified_by_name" in self.model_fields_set:
            _dict['last_modified_by_name'] = None

        # set to None if last_modified_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by_user_id is None and "last_modified_by_user_id" in self.model_fields_set:
            _dict['last_modified_by_user_id'] = None

        # set to None if billing_note (nullable) is None
        # and model_fields_set contains the field
        if self.billing_note is None and "billing_note" in self.model_fields_set:
            _dict['billing_note'] = None

        # set to None if billing_reason (nullable) is None
        # and model_fields_set contains the field
        if self.billing_reason is None and "billing_reason" in self.model_fields_set:
            _dict['billing_reason'] = None

        # set to None if catalog_id (nullable) is None
        # and model_fields_set contains the field
        if self.catalog_id is None and "catalog_id" in self.model_fields_set:
            _dict['catalog_id'] = None

        # set to None if catalog_slug (nullable) is None
        # and model_fields_set contains the field
        if self.catalog_slug is None and "catalog_slug" in self.model_fields_set:
            _dict['catalog_slug'] = None

        # set to None if connection_id (nullable) is None
        # and model_fields_set contains the field
        if self.connection_id is None and "connection_id" in self.model_fields_set:
            _dict['connection_id'] = None

        # set to None if health_checked_at (nullable) is None
        # and model_fields_set contains the field
        if self.health_checked_at is None and "health_checked_at" in self.model_fields_set:
            _dict['health_checked_at'] = None

        # set to None if health_detail (nullable) is None
        # and model_fields_set contains the field
        if self.health_detail is None and "health_detail" in self.model_fields_set:
            _dict['health_detail'] = None

        # set to None if request_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.request_timeout_secs is None and "request_timeout_secs" in self.model_fields_set:
            _dict['request_timeout_secs'] = None

        # set to None if settings (nullable) is None
        # and model_fields_set contains the field
        if self.settings is None and "settings" in self.model_fields_set:
            _dict['settings'] = None

        # set to None if stream_idle_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.stream_idle_timeout_secs is None and "stream_idle_timeout_secs" in self.model_fields_set:
            _dict['stream_idle_timeout_secs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Provider from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_by_email": obj.get("created_by_email"),
            "created_by_name": obj.get("created_by_name"),
            "created_by_user_id": obj.get("created_by_user_id"),
            "last_change_note": obj.get("last_change_note"),
            "last_modified_at": obj.get("last_modified_at"),
            "last_modified_by_email": obj.get("last_modified_by_email"),
            "last_modified_by_name": obj.get("last_modified_by_name"),
            "last_modified_by_user_id": obj.get("last_modified_by_user_id"),
            "auth_type": obj.get("auth_type"),
            "base_url": obj.get("base_url"),
            "billing_mode": obj.get("billing_mode"),
            "billing_note": obj.get("billing_note"),
            "billing_reason": obj.get("billing_reason"),
            "catalog_id": obj.get("catalog_id"),
            "catalog_slug": obj.get("catalog_slug"),
            "connection_id": obj.get("connection_id"),
            "created_at": obj.get("created_at"),
            "enabled": obj.get("enabled"),
            "enforce_health_check": obj.get("enforce_health_check"),
            "health_checked_at": obj.get("health_checked_at"),
            "health_detail": obj.get("health_detail"),
            "health_status": obj.get("health_status"),
            "id": obj.get("id"),
            "model_provider": obj.get("model_provider"),
            "model_sync_mode": obj.get("model_sync_mode"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "request_timeout_secs": obj.get("request_timeout_secs"),
            "secret_path": obj.get("secret_path"),
            "settings": obj.get("settings"),
            "stream_idle_timeout_secs": obj.get("stream_idle_timeout_secs"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


