# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from barndoor.models.attention_tier import AttentionTier
from barndoor.models.mcp_server_directory_base import MCPServerDirectoryBase
from barndoor.models.publish_blocker import PublishBlocker
from barndoor.models.server_connection_response import ServerConnectionResponse
from barndoor.models.server_connection_status import ServerConnectionStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ServerResponse(BaseModel):
    """
    Response model for MCP server with computed fields.  This model includes both database fields and computed fields like connection_status, url, and proxy_url that are added at runtime.
    """ # noqa: E501
    id: UUID
    created_at: datetime
    updated_at: datetime
    name: StrictStr
    slug: StrictStr
    oauth_base_url_override: Optional[StrictStr]
    client_id: Optional[Annotated[str, Field(strict=True, max_length=255)]]
    client_secret: Optional[StrictStr]
    uses_managed_credentials: Optional[StrictBool]
    scopes: Optional[List[StrictStr]]
    organization_id: Optional[UUID]
    mcp_server_directory_id: UUID
    status: StrictStr
    meta: Optional[Any]
    tools_fetch_status: StrictStr
    tools_fetch_error: Optional[Any]
    tools_fetched_at: Optional[datetime]
    tools_fetch_requested_at: Optional[datetime]
    published_at: Optional[datetime]
    mcp_server_directory: MCPServerDirectoryBase
    mcp_server_service_connection: Optional[ServerConnectionResponse]
    connection_status: Optional[ServerConnectionStatus]
    url: Optional[StrictStr]
    proxy_url: Optional[StrictStr]
    can_manage_policies: Optional[StrictBool]
    attention_tier: Optional[AttentionTier]
    publish_blockers: Optional[List[PublishBlocker]]
    cascaded_fields: Optional[List[StrictStr]]
    deleted_at: Optional[datetime]
    tools_count: StrictInt
    resources_count: StrictInt
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "name", "slug", "oauth_base_url_override", "client_id", "client_secret", "uses_managed_credentials", "scopes", "organization_id", "mcp_server_directory_id", "status", "meta", "tools_fetch_status", "tools_fetch_error", "tools_fetched_at", "tools_fetch_requested_at", "published_at", "mcp_server_directory", "mcp_server_service_connection", "connection_status", "url", "proxy_url", "can_manage_policies", "attention_tier", "publish_blockers", "cascaded_fields", "deleted_at", "tools_count", "resources_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "tools_count",
            "resources_count",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mcp_server_directory
        if self.mcp_server_directory:
            _dict['mcp_server_directory'] = self.mcp_server_directory.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mcp_server_service_connection
        if self.mcp_server_service_connection:
            _dict['mcp_server_service_connection'] = self.mcp_server_service_connection.to_dict()
        # set to None if oauth_base_url_override (nullable) is None
        # and model_fields_set contains the field
        if self.oauth_base_url_override is None and "oauth_base_url_override" in self.model_fields_set:
            _dict['oauth_base_url_override'] = None

        # set to None if client_id (nullable) is None
        # and model_fields_set contains the field
        if self.client_id is None and "client_id" in self.model_fields_set:
            _dict['client_id'] = None

        # set to None if client_secret (nullable) is None
        # and model_fields_set contains the field
        if self.client_secret is None and "client_secret" in self.model_fields_set:
            _dict['client_secret'] = None

        # set to None if uses_managed_credentials (nullable) is None
        # and model_fields_set contains the field
        if self.uses_managed_credentials is None and "uses_managed_credentials" in self.model_fields_set:
            _dict['uses_managed_credentials'] = None

        # set to None if scopes (nullable) is None
        # and model_fields_set contains the field
        if self.scopes is None and "scopes" in self.model_fields_set:
            _dict['scopes'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organization_id'] = None

        # set to None if meta (nullable) is None
        # and model_fields_set contains the field
        if self.meta is None and "meta" in self.model_fields_set:
            _dict['meta'] = None

        # set to None if tools_fetch_error (nullable) is None
        # and model_fields_set contains the field
        if self.tools_fetch_error is None and "tools_fetch_error" in self.model_fields_set:
            _dict['tools_fetch_error'] = None

        # set to None if tools_fetched_at (nullable) is None
        # and model_fields_set contains the field
        if self.tools_fetched_at is None and "tools_fetched_at" in self.model_fields_set:
            _dict['tools_fetched_at'] = None

        # set to None if tools_fetch_requested_at (nullable) is None
        # and model_fields_set contains the field
        if self.tools_fetch_requested_at is None and "tools_fetch_requested_at" in self.model_fields_set:
            _dict['tools_fetch_requested_at'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['published_at'] = None

        # set to None if mcp_server_service_connection (nullable) is None
        # and model_fields_set contains the field
        if self.mcp_server_service_connection is None and "mcp_server_service_connection" in self.model_fields_set:
            _dict['mcp_server_service_connection'] = None

        # set to None if connection_status (nullable) is None
        # and model_fields_set contains the field
        if self.connection_status is None and "connection_status" in self.model_fields_set:
            _dict['connection_status'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if proxy_url (nullable) is None
        # and model_fields_set contains the field
        if self.proxy_url is None and "proxy_url" in self.model_fields_set:
            _dict['proxy_url'] = None

        # set to None if can_manage_policies (nullable) is None
        # and model_fields_set contains the field
        if self.can_manage_policies is None and "can_manage_policies" in self.model_fields_set:
            _dict['can_manage_policies'] = None

        # set to None if attention_tier (nullable) is None
        # and model_fields_set contains the field
        if self.attention_tier is None and "attention_tier" in self.model_fields_set:
            _dict['attention_tier'] = None

        # set to None if publish_blockers (nullable) is None
        # and model_fields_set contains the field
        if self.publish_blockers is None and "publish_blockers" in self.model_fields_set:
            _dict['publish_blockers'] = None

        # set to None if cascaded_fields (nullable) is None
        # and model_fields_set contains the field
        if self.cascaded_fields is None and "cascaded_fields" in self.model_fields_set:
            _dict['cascaded_fields'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "oauth_base_url_override": obj.get("oauth_base_url_override"),
            "client_id": obj.get("client_id"),
            "client_secret": obj.get("client_secret"),
            "uses_managed_credentials": obj.get("uses_managed_credentials"),
            "scopes": obj.get("scopes"),
            "organization_id": obj.get("organization_id"),
            "mcp_server_directory_id": obj.get("mcp_server_directory_id"),
            "status": obj.get("status"),
            "meta": obj.get("meta"),
            "tools_fetch_status": obj.get("tools_fetch_status"),
            "tools_fetch_error": obj.get("tools_fetch_error"),
            "tools_fetched_at": obj.get("tools_fetched_at"),
            "tools_fetch_requested_at": obj.get("tools_fetch_requested_at"),
            "published_at": obj.get("published_at"),
            "mcp_server_directory": MCPServerDirectoryBase.from_dict(obj["mcp_server_directory"]) if obj.get("mcp_server_directory") is not None else None,
            "mcp_server_service_connection": ServerConnectionResponse.from_dict(obj["mcp_server_service_connection"]) if obj.get("mcp_server_service_connection") is not None else None,
            "connection_status": obj.get("connection_status"),
            "url": obj.get("url"),
            "proxy_url": obj.get("proxy_url"),
            "can_manage_policies": obj.get("can_manage_policies"),
            "attention_tier": obj.get("attention_tier"),
            "publish_blockers": obj.get("publish_blockers"),
            "cascaded_fields": obj.get("cascaded_fields"),
            "deleted_at": obj.get("deleted_at"),
            "tools_count": obj.get("tools_count"),
            "resources_count": obj.get("resources_count")
        })
        return _obj


