# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ServerConnectionResponse(BaseModel):
    """
    Public service-connection shape exposed from server endpoints.
    """ # noqa: E501
    id: UUID
    mcp_server_id: UUID
    user_id: Optional[StrictStr] = None
    application_id: Optional[UUID] = None
    status: StrictStr
    error_message: Optional[StrictStr] = None
    created_at: datetime
    connected_at: Optional[datetime] = None
    last_accessed_at: Optional[datetime] = None
    connected_by_user_id: Optional[StrictStr] = None
    account_email: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "mcp_server_id", "user_id", "application_id", "status", "error_message", "created_at", "connected_at", "last_accessed_at", "connected_by_user_id", "account_email"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerConnectionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if application_id (nullable) is None
        # and model_fields_set contains the field
        if self.application_id is None and "application_id" in self.model_fields_set:
            _dict['application_id'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if connected_at (nullable) is None
        # and model_fields_set contains the field
        if self.connected_at is None and "connected_at" in self.model_fields_set:
            _dict['connected_at'] = None

        # set to None if last_accessed_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_accessed_at is None and "last_accessed_at" in self.model_fields_set:
            _dict['last_accessed_at'] = None

        # set to None if connected_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.connected_by_user_id is None and "connected_by_user_id" in self.model_fields_set:
            _dict['connected_by_user_id'] = None

        # set to None if account_email (nullable) is None
        # and model_fields_set contains the field
        if self.account_email is None and "account_email" in self.model_fields_set:
            _dict['account_email'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerConnectionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "mcp_server_id": obj.get("mcp_server_id"),
            "user_id": obj.get("user_id"),
            "application_id": obj.get("application_id"),
            "status": obj.get("status"),
            "error_message": obj.get("error_message"),
            "created_at": obj.get("created_at"),
            "connected_at": obj.get("connected_at"),
            "last_accessed_at": obj.get("last_accessed_at"),
            "connected_by_user_id": obj.get("connected_by_user_id"),
            "account_email": obj.get("account_email")
        })
        return _obj


