# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StaleReason(str, Enum):
    """
    StaleReason
    """

    """
    allowed enum values
    """
    CATALOG_REMOVED = 'catalog_removed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StaleReason from a JSON string"""
        return cls(json.loads(json_str))


