# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from barndoor.models.resolved_protection_response import ResolvedProtectionResponse
from barndoor.models.test_finding_response import TestFindingResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestProcessTextResponse(BaseModel):
    """
    TestProcessTextResponse
    """ # noqa: E501
    block_reason: Optional[StrictStr] = None
    duration_ms: Annotated[int, Field(strict=True, ge=0)]
    findings: List[TestFindingResponse]
    processed_structured_payload_json: Optional[StrictStr] = None
    processed_text: StrictStr
    resolved_policy: ResolvedProtectionResponse
    verdict: StrictStr
    __properties: ClassVar[List[str]] = ["block_reason", "duration_ms", "findings", "processed_structured_payload_json", "processed_text", "resolved_policy", "verdict"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestProcessTextResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in findings (list)
        _items = []
        if self.findings:
            for _item_findings in self.findings:
                _items.append(_item_findings.to_dict() if _item_findings is not None else None)
            _dict['findings'] = _items
        # override the default output from pydantic by calling `to_dict()` of resolved_policy
        if self.resolved_policy:
            _dict['resolved_policy'] = self.resolved_policy.to_dict()
        # set to None if block_reason (nullable) is None
        # and model_fields_set contains the field
        if self.block_reason is None and "block_reason" in self.model_fields_set:
            _dict['block_reason'] = None

        # set to None if processed_structured_payload_json (nullable) is None
        # and model_fields_set contains the field
        if self.processed_structured_payload_json is None and "processed_structured_payload_json" in self.model_fields_set:
            _dict['processed_structured_payload_json'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestProcessTextResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_reason": obj.get("block_reason"),
            "duration_ms": obj.get("duration_ms"),
            "findings": [TestFindingResponse.from_dict(_item) for _item in obj["findings"]] if obj.get("findings") is not None else None,
            "processed_structured_payload_json": obj.get("processed_structured_payload_json"),
            "processed_text": obj.get("processed_text"),
            "resolved_policy": ResolvedProtectionResponse.from_dict(obj["resolved_policy"]) if obj.get("resolved_policy") is not None else None,
            "verdict": obj.get("verdict")
        })
        return _obj


