# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from barndoor.models.long_context_tier_request import LongContextTierRequest
from barndoor.models.pricing_sync_mode import PricingSyncMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdatePricingRequest(BaseModel):
    """
    UpdatePricingRequest
    """ # noqa: E501
    cache_read_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Update prompt-cache rates. Same NULL semantics as `CreatePricingRequest`: omitted = leave existing value alone; JSON `null` = explicitly clear the override.")
    cache_write_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = None
    change_reason: Optional[StrictStr] = None
    effective_from: Optional[datetime] = Field(default=None, description="Reschedule the activation date. Past values are rejected by the db layer's `update_scheduled` guard, but a future timestamp is fine and a near-`now()` timestamp effectively \"activates now\".")
    input_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = None
    long_context: Optional[LongContextTierRequest] = Field(default=None, description="Update the long-context surcharge (BCP-3904). Same three-state semantics as the cache rates: omitted = leave the tier alone, JSON `null` = remove the tier entirely, an object = set it.  The tier moves as a unit, so `null` clears the threshold and every tier rate together — there is no way to null out one tier rate while keeping the others, which is what the DB constraint requires anyway.")
    output_cost_per_million_tokens: Optional[Union[StrictFloat, StrictInt]] = None
    sync_mode: Optional[PricingSyncMode] = Field(default=None, description="Omit (or pass `null`) to leave the mode unchanged.")
    __properties: ClassVar[List[str]] = ["cache_read_cost_per_million_tokens", "cache_write_cost_per_million_tokens", "change_reason", "effective_from", "input_cost_per_million_tokens", "long_context", "output_cost_per_million_tokens", "sync_mode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdatePricingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of long_context
        if self.long_context:
            _dict['long_context'] = self.long_context.to_dict()
        # set to None if cache_read_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_read_cost_per_million_tokens is None and "cache_read_cost_per_million_tokens" in self.model_fields_set:
            _dict['cache_read_cost_per_million_tokens'] = None

        # set to None if cache_write_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.cache_write_cost_per_million_tokens is None and "cache_write_cost_per_million_tokens" in self.model_fields_set:
            _dict['cache_write_cost_per_million_tokens'] = None

        # set to None if change_reason (nullable) is None
        # and model_fields_set contains the field
        if self.change_reason is None and "change_reason" in self.model_fields_set:
            _dict['change_reason'] = None

        # set to None if effective_from (nullable) is None
        # and model_fields_set contains the field
        if self.effective_from is None and "effective_from" in self.model_fields_set:
            _dict['effective_from'] = None

        # set to None if input_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.input_cost_per_million_tokens is None and "input_cost_per_million_tokens" in self.model_fields_set:
            _dict['input_cost_per_million_tokens'] = None

        # set to None if long_context (nullable) is None
        # and model_fields_set contains the field
        if self.long_context is None and "long_context" in self.model_fields_set:
            _dict['long_context'] = None

        # set to None if output_cost_per_million_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.output_cost_per_million_tokens is None and "output_cost_per_million_tokens" in self.model_fields_set:
            _dict['output_cost_per_million_tokens'] = None

        # set to None if sync_mode (nullable) is None
        # and model_fields_set contains the field
        if self.sync_mode is None and "sync_mode" in self.model_fields_set:
            _dict['sync_mode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdatePricingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache_read_cost_per_million_tokens": obj.get("cache_read_cost_per_million_tokens"),
            "cache_write_cost_per_million_tokens": obj.get("cache_write_cost_per_million_tokens"),
            "change_reason": obj.get("change_reason"),
            "effective_from": obj.get("effective_from"),
            "input_cost_per_million_tokens": obj.get("input_cost_per_million_tokens"),
            "long_context": LongContextTierRequest.from_dict(obj["long_context"]) if obj.get("long_context") is not None else None,
            "output_cost_per_million_tokens": obj.get("output_cost_per_million_tokens"),
            "sync_mode": obj.get("sync_mode")
        })
        return _obj


