# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateModelMappingRequest(BaseModel):
    """
    UpdateModelMappingRequest
    """ # noqa: E501
    bare_alias: Optional[StrictBool] = None
    change_note: Optional[StrictStr] = Field(default=None, description="Optional free-text note explaining why this edit was made (BCP-3998).  Deliberately *not* tri-state like the timeout overrides above: omitting it clears the previous note, because the note describes the latest change and an unrelated later edit must not inherit an explanation written for a different one.")
    cooldown_429_default_secs: Optional[StrictInt] = Field(default=None, description="Cooldown on an upstream 429 that carries no usable `Retry-After` (a `Retry-After` sets the window instead). Range 1-3600, and at most `cooldown_max_secs`; default 30.  Omitted (or `null`) keeps the stored value.")
    cooldown_base_secs: Optional[StrictInt] = Field(default=None, description="First cooldown window once the threshold trips, doubled on each failed recovery probe up to `cooldown_max_secs`. Range 1-3600, and at most `cooldown_max_secs`; default 30.  Omitted (or `null`) keeps the stored value.")
    cooldown_failure_threshold: Optional[StrictInt] = Field(default=None, description="Gateway failures (5xx, timeouts, connection errors, managed-key 401/403) within `cooldown_window_secs` that cool the route. `0` disables every cooldown of the shared route (rolling failures, 429 and 529); per-user credential cooldowns on passthrough routes still apply. Range 0-100; default 10.  Omitted (or `null`) keeps the stored value.")
    cooldown_max_secs: Optional[StrictInt] = Field(default=None, description="Cap on every cooldown window: doubling, 429 and 529. Range 1-86400; default 300.  Omitted (or `null`) keeps the stored value.")
    cooldown_overloaded_secs: Optional[StrictInt] = Field(default=None, description="Flat cooldown on an upstream 529 \"overloaded\" with no usable `Retry-After`; it does not spend the failure budget. `0` counts a 529 as an ordinary gateway failure instead. Range 0-3600, and at most `cooldown_max_secs` unless 0; default 10.  Omitted (or `null`) keeps the stored value.")
    cooldown_window_secs: Optional[StrictInt] = Field(default=None, description="Width of the rolling failure window, seconds. Range 1-3600; default 60.  Omitted (or `null`) keeps the stored value.")
    enabled: Optional[StrictBool] = None
    model_alias: Optional[StrictStr] = None
    priority: Optional[StrictInt] = None
    request_timeout_secs: Optional[StrictInt] = Field(default=None, description="`None` (omitted) leaves the column unchanged. `Some(None)` (JSON `null`) clears the override. `Some(Some(secs))` sets the non-streaming total-request timeout; the range is fixed platform policy (`TOTAL_REQUEST_TIMEOUT_MIN_SECS..=TOTAL_REQUEST_TIMEOUT_MAX_SECS`, see [`crate::proxy::timeouts`]).")
    retry_on_429_count: Optional[StrictInt] = None
    retry_on_429_max_wait_secs: Optional[StrictInt] = None
    stream_idle_timeout_secs: Optional[StrictInt] = Field(default=None, description="`None` (omitted) leaves the column unchanged. `Some(None)` (JSON `null`) clears the override. `Some(Some(secs))` sets the streaming per-chunk timeout; the range is fixed platform policy (`STREAM_IDLE_TIMEOUT_MIN_SECS..=STREAM_IDLE_TIMEOUT_MAX_SECS`, see [`crate::proxy::timeouts`]).")
    upstream_model: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["bare_alias", "change_note", "cooldown_429_default_secs", "cooldown_base_secs", "cooldown_failure_threshold", "cooldown_max_secs", "cooldown_overloaded_secs", "cooldown_window_secs", "enabled", "model_alias", "priority", "request_timeout_secs", "retry_on_429_count", "retry_on_429_max_wait_secs", "stream_idle_timeout_secs", "upstream_model"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateModelMappingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if bare_alias (nullable) is None
        # and model_fields_set contains the field
        if self.bare_alias is None and "bare_alias" in self.model_fields_set:
            _dict['bare_alias'] = None

        # set to None if change_note (nullable) is None
        # and model_fields_set contains the field
        if self.change_note is None and "change_note" in self.model_fields_set:
            _dict['change_note'] = None

        # set to None if cooldown_429_default_secs (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_429_default_secs is None and "cooldown_429_default_secs" in self.model_fields_set:
            _dict['cooldown_429_default_secs'] = None

        # set to None if cooldown_base_secs (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_base_secs is None and "cooldown_base_secs" in self.model_fields_set:
            _dict['cooldown_base_secs'] = None

        # set to None if cooldown_failure_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_failure_threshold is None and "cooldown_failure_threshold" in self.model_fields_set:
            _dict['cooldown_failure_threshold'] = None

        # set to None if cooldown_max_secs (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_max_secs is None and "cooldown_max_secs" in self.model_fields_set:
            _dict['cooldown_max_secs'] = None

        # set to None if cooldown_overloaded_secs (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_overloaded_secs is None and "cooldown_overloaded_secs" in self.model_fields_set:
            _dict['cooldown_overloaded_secs'] = None

        # set to None if cooldown_window_secs (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_window_secs is None and "cooldown_window_secs" in self.model_fields_set:
            _dict['cooldown_window_secs'] = None

        # set to None if enabled (nullable) is None
        # and model_fields_set contains the field
        if self.enabled is None and "enabled" in self.model_fields_set:
            _dict['enabled'] = None

        # set to None if model_alias (nullable) is None
        # and model_fields_set contains the field
        if self.model_alias is None and "model_alias" in self.model_fields_set:
            _dict['model_alias'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if request_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.request_timeout_secs is None and "request_timeout_secs" in self.model_fields_set:
            _dict['request_timeout_secs'] = None

        # set to None if retry_on_429_count (nullable) is None
        # and model_fields_set contains the field
        if self.retry_on_429_count is None and "retry_on_429_count" in self.model_fields_set:
            _dict['retry_on_429_count'] = None

        # set to None if retry_on_429_max_wait_secs (nullable) is None
        # and model_fields_set contains the field
        if self.retry_on_429_max_wait_secs is None and "retry_on_429_max_wait_secs" in self.model_fields_set:
            _dict['retry_on_429_max_wait_secs'] = None

        # set to None if stream_idle_timeout_secs (nullable) is None
        # and model_fields_set contains the field
        if self.stream_idle_timeout_secs is None and "stream_idle_timeout_secs" in self.model_fields_set:
            _dict['stream_idle_timeout_secs'] = None

        # set to None if upstream_model (nullable) is None
        # and model_fields_set contains the field
        if self.upstream_model is None and "upstream_model" in self.model_fields_set:
            _dict['upstream_model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateModelMappingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bare_alias": obj.get("bare_alias"),
            "change_note": obj.get("change_note"),
            "cooldown_429_default_secs": obj.get("cooldown_429_default_secs"),
            "cooldown_base_secs": obj.get("cooldown_base_secs"),
            "cooldown_failure_threshold": obj.get("cooldown_failure_threshold"),
            "cooldown_max_secs": obj.get("cooldown_max_secs"),
            "cooldown_overloaded_secs": obj.get("cooldown_overloaded_secs"),
            "cooldown_window_secs": obj.get("cooldown_window_secs"),
            "enabled": obj.get("enabled"),
            "model_alias": obj.get("model_alias"),
            "priority": obj.get("priority"),
            "request_timeout_secs": obj.get("request_timeout_secs"),
            "retry_on_429_count": obj.get("retry_on_429_count"),
            "retry_on_429_max_wait_secs": obj.get("retry_on_429_max_wait_secs"),
            "stream_idle_timeout_secs": obj.get("stream_idle_timeout_secs"),
            "upstream_model": obj.get("upstream_model")
        })
        return _obj


