# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpsertAwsBedrockGuardrailsRequest(BaseModel):
    """
    UpsertAwsBedrockGuardrailsRequest
    """ # noqa: E501
    access_key_id: Optional[StrictStr] = None
    auth_type: Optional[StrictStr] = None
    endpoint: Optional[StrictStr] = None
    external_id: Optional[StrictStr] = None
    guardrail_identifier: StrictStr
    guardrail_version: Optional[StrictStr] = None
    iam_role_arn: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    secret_access_key: Optional[StrictStr] = Field(default=None, description="Supply to set or rotate the AWS secret; omit to leave unchanged.")
    session_token: Optional[StrictStr] = Field(default=None, description="Optional AWS session token stored with the secret access key.")
    __properties: ClassVar[List[str]] = ["access_key_id", "auth_type", "endpoint", "external_id", "guardrail_identifier", "guardrail_version", "iam_role_arn", "region", "secret_access_key", "session_token"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpsertAwsBedrockGuardrailsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if access_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.access_key_id is None and "access_key_id" in self.model_fields_set:
            _dict['access_key_id'] = None

        # set to None if auth_type (nullable) is None
        # and model_fields_set contains the field
        if self.auth_type is None and "auth_type" in self.model_fields_set:
            _dict['auth_type'] = None

        # set to None if endpoint (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint is None and "endpoint" in self.model_fields_set:
            _dict['endpoint'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if iam_role_arn (nullable) is None
        # and model_fields_set contains the field
        if self.iam_role_arn is None and "iam_role_arn" in self.model_fields_set:
            _dict['iam_role_arn'] = None

        # set to None if secret_access_key (nullable) is None
        # and model_fields_set contains the field
        if self.secret_access_key is None and "secret_access_key" in self.model_fields_set:
            _dict['secret_access_key'] = None

        # set to None if session_token (nullable) is None
        # and model_fields_set contains the field
        if self.session_token is None and "session_token" in self.model_fields_set:
            _dict['session_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpsertAwsBedrockGuardrailsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_key_id": obj.get("access_key_id"),
            "auth_type": obj.get("auth_type"),
            "endpoint": obj.get("endpoint"),
            "external_id": obj.get("external_id"),
            "guardrail_identifier": obj.get("guardrail_identifier"),
            "guardrail_version": obj.get("guardrail_version"),
            "iam_role_arn": obj.get("iam_role_arn"),
            "region": obj.get("region"),
            "secret_access_key": obj.get("secret_access_key"),
            "session_token": obj.get("session_token")
        })
        return _obj


