# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from barndoor.models.budget_action import BudgetAction
from barndoor.models.budget_period import BudgetPeriod
from barndoor.models.scope_type import ScopeType
from barndoor.models.traffic_type import TrafficType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WithAttributionTokenBudget(BaseModel):
    """
    An admin-API response for an entity whose core type lives in `ai_governance` and so cannot carry portal-only columns.  `TokenBudget` and `RateLimitPolicy` are read by the enforcement path on every request; hanging five display-only fields off them would put portal concerns in the hot path's type and force every governance consumer to carry them. Wrapping instead keeps the enforcement reads (`get_enabled_by_org` and friends) returning the bare governance type, while the admin reads return this.  Both halves are `#[serde(flatten)]`, so the wire shape stays the flat object the portal already consumes — same choice `AdminModelPricing` makes.
    """ # noqa: E501
    created_by_email: Optional[StrictStr] = None
    created_by_name: Optional[StrictStr] = None
    created_by_user_id: Optional[UUID] = None
    last_change_note: Optional[StrictStr] = Field(default=None, description="Optional free text explaining *why* the last change was made (\"Raised for the Q3 batch job\", \"Vendor deprecated the old endpoint\").  Admin-authored and rendered in the portal, so it is untrusted input: length-capped here, escaped on render.")
    last_modified_at: Optional[datetime] = Field(default=None, description="When the change named by `last_modified_by_*` happened.  Its own column rather than the row's `updated_at`, because `updated_at` is bumped by writes nobody is attributed for -- pairing the two would date a named admin's edit to a background job's clock. See the V75 migration for the full reasoning.")
    last_modified_by_email: Optional[StrictStr] = None
    last_modified_by_name: Optional[StrictStr] = None
    last_modified_by_user_id: Optional[UUID] = None
    action_on_exhaust: BudgetAction
    alert_thresholds: List[StrictInt]
    cost_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Optional spending cap in the configured currency. When set, the budget is enforced on estimated cost in addition to tokens.")
    created_at: Optional[datetime] = Field(default=None, description="When the budget was created. Populated on the admin API path (where it is surfaced in the dashboard); left `None` on the hot enforcement path and in fixtures, which don't need it. `#[serde(default)]` keeps older payloads without the field deserializing cleanly.")
    currency: Optional[StrictStr] = Field(default=None, description="ISO 4217 currency code (e.g. \"USD\"). Defaults to \"USD\".")
    enabled: StrictBool
    id: UUID
    member_of_group: Optional[StrictStr] = Field(default=None, description="BCP-3814 membership filter: when set, this budget only applies to requesters whose IdP group membership includes this group name.  Only meaningful on a broad user-scoped budget (`scope_type == User` with `scope_id` and `scope_value` both `None`), where the counter qualifier already resolves to the requesting user's id — so one budget row gives every *member of the group* their own independent allowance, and a user joining the group is enforced on their next request with no admin action. DB-enforced by `token_budgets_member_of_group_requires_broad_user` (V65, tightened to exclude `scope_value` by V67).  `None` ⇒ the budget applies org-wide (the pre-BCP-3814 behaviour). Contrast with a `ScopeType::Group` budget, which keys its counter by the group name and so *pools* one allowance across all members.")
    name: StrictStr
    org_id: UUID
    period: BudgetPeriod
    scope_id: Optional[UUID] = None
    scope_type: ScopeType
    scope_value: Optional[StrictStr] = None
    target_mcp_server_id: Optional[UUID] = Field(default=None, description="BCP-4053 Target dimension: when set, the budget only fires on requests routed to this MCP server. The MCP-traffic counterpart of `target_provider_id`, and mutually exclusive with all three LLM target columns (DB-enforced by `token_budgets_mcp_target_exclusive_check`) — no single request carries both an MCP server and an LLM route, so a row naming both could never match.  Distinct from a `ScopeType::McpServer` budget, which puts the server on the *identity* axis and so cannot be combined with a user or group. As a target it composes freely with any scope, which is what makes \"this user's cap on this server\" expressible.")
    target_model_alias: Optional[StrictStr] = Field(default=None, description="BCP-2813 Target dimension: when set, the budget only fires when the requested model alias (`request.model`) equals this value. Mutually exclusive with the other two `target_*` fields.")
    target_provider_id: Optional[UUID] = Field(default=None, description="BCP-2813 Target dimension: when set, the budget only fires on routes whose provider id equals this value. May be combined with `target_upstream_model` to cap a single model on this provider; mutually exclusive with `target_model_alias` (DB-enforced by `token_budgets_alias_target_exclusive_check`).")
    target_upstream_model: Optional[StrictStr] = Field(default=None, description="BCP-2813 Target dimension refining `target_provider_id`: when set, the budget only fires on routes whose resolved upstream model name equals this value (string match). Always set alongside a provider (V54 CHECK-enforced) — a bare upstream name would string every provider serving that model into one cap.")
    token_limit: StrictInt
    traffic_type: TrafficType
    __properties: ClassVar[List[str]] = ["created_by_email", "created_by_name", "created_by_user_id", "last_change_note", "last_modified_at", "last_modified_by_email", "last_modified_by_name", "last_modified_by_user_id", "action_on_exhaust", "alert_thresholds", "cost_limit", "created_at", "currency", "enabled", "id", "member_of_group", "name", "org_id", "period", "scope_id", "scope_type", "scope_value", "target_mcp_server_id", "target_model_alias", "target_provider_id", "target_upstream_model", "token_limit", "traffic_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WithAttributionTokenBudget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cost_limit (nullable) is None
        # and model_fields_set contains the field
        if self.cost_limit is None and "cost_limit" in self.model_fields_set:
            _dict['cost_limit'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if member_of_group (nullable) is None
        # and model_fields_set contains the field
        if self.member_of_group is None and "member_of_group" in self.model_fields_set:
            _dict['member_of_group'] = None

        # set to None if scope_id (nullable) is None
        # and model_fields_set contains the field
        if self.scope_id is None and "scope_id" in self.model_fields_set:
            _dict['scope_id'] = None

        # set to None if scope_value (nullable) is None
        # and model_fields_set contains the field
        if self.scope_value is None and "scope_value" in self.model_fields_set:
            _dict['scope_value'] = None

        # set to None if target_mcp_server_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_mcp_server_id is None and "target_mcp_server_id" in self.model_fields_set:
            _dict['target_mcp_server_id'] = None

        # set to None if target_model_alias (nullable) is None
        # and model_fields_set contains the field
        if self.target_model_alias is None and "target_model_alias" in self.model_fields_set:
            _dict['target_model_alias'] = None

        # set to None if target_provider_id (nullable) is None
        # and model_fields_set contains the field
        if self.target_provider_id is None and "target_provider_id" in self.model_fields_set:
            _dict['target_provider_id'] = None

        # set to None if target_upstream_model (nullable) is None
        # and model_fields_set contains the field
        if self.target_upstream_model is None and "target_upstream_model" in self.model_fields_set:
            _dict['target_upstream_model'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WithAttributionTokenBudget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_by_email": obj.get("created_by_email"),
            "created_by_name": obj.get("created_by_name"),
            "created_by_user_id": obj.get("created_by_user_id"),
            "last_change_note": obj.get("last_change_note"),
            "last_modified_at": obj.get("last_modified_at"),
            "last_modified_by_email": obj.get("last_modified_by_email"),
            "last_modified_by_name": obj.get("last_modified_by_name"),
            "last_modified_by_user_id": obj.get("last_modified_by_user_id"),
            "action_on_exhaust": obj.get("action_on_exhaust"),
            "alert_thresholds": obj.get("alert_thresholds"),
            "cost_limit": obj.get("cost_limit"),
            "created_at": obj.get("created_at"),
            "currency": obj.get("currency"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "member_of_group": obj.get("member_of_group"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "period": obj.get("period"),
            "scope_id": obj.get("scope_id"),
            "scope_type": obj.get("scope_type"),
            "scope_value": obj.get("scope_value"),
            "target_mcp_server_id": obj.get("target_mcp_server_id"),
            "target_model_alias": obj.get("target_model_alias"),
            "target_provider_id": obj.get("target_provider_id"),
            "target_upstream_model": obj.get("target_upstream_model"),
            "token_limit": obj.get("token_limit"),
            "traffic_type": obj.get("traffic_type")
        })
        return _obj
