# coding: utf-8

"""
    Barndoor.ai Public API

    Unified public API specification for Barndoor.ai platform

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from barndoor.models.model_access_target import ModelAccessTarget
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WithAttributionModelAccessPolicy(BaseModel):
    """
    An admin-API response for an entity whose core type lives in `ai_governance` and so cannot carry portal-only columns.  `TokenBudget` and `RateLimitPolicy` are read by the enforcement path on every request; hanging five display-only fields off them would put portal concerns in the hot path's type and force every governance consumer to carry them. Wrapping instead keeps the enforcement reads (`get_enabled_by_org` and friends) returning the bare governance type, while the admin reads return this.  Both halves are `#[serde(flatten)]`, so the wire shape stays the flat object the portal already consumes — same choice `AdminModelPricing` makes.
    """ # noqa: E501
    created_by_email: Optional[StrictStr] = None
    created_by_name: Optional[StrictStr] = None
    created_by_user_id: Optional[UUID] = None
    last_change_note: Optional[StrictStr] = Field(default=None, description="Optional free text explaining *why* the last change was made (\"Raised for the Q3 batch job\", \"Vendor deprecated the old endpoint\").  Admin-authored and rendered in the portal, so it is untrusted input: length-capped here, escaped on render.")
    last_modified_at: Optional[datetime] = Field(default=None, description="When the change named by `last_modified_by_*` happened.  Its own column rather than the row's `updated_at`, because `updated_at` is bumped by writes nobody is attributed for -- pairing the two would date a named admin's edit to a background job's clock. See the V75 migration for the full reasoning.")
    last_modified_by_email: Optional[StrictStr] = None
    last_modified_by_name: Optional[StrictStr] = None
    last_modified_by_user_id: Optional[UUID] = None
    enabled: StrictBool
    id: UUID
    name: StrictStr
    org_id: UUID
    policy_type: StrictStr
    scope_id: Optional[UUID] = None
    scope_type: StrictStr
    scope_value: Optional[StrictStr] = None
    targets: List[ModelAccessTarget]
    traffic_type: StrictStr
    __properties: ClassVar[List[str]] = ["created_by_email", "created_by_name", "created_by_user_id", "last_change_note", "last_modified_at", "last_modified_by_email", "last_modified_by_name", "last_modified_by_user_id", "enabled", "id", "name", "org_id", "policy_type", "scope_id", "scope_type", "scope_value", "targets", "traffic_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WithAttributionModelAccessPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in targets (list)
        _items = []
        if self.targets:
            for _item_targets in self.targets:
                _items.append(_item_targets.to_dict() if _item_targets is not None else None)
            _dict['targets'] = _items
        # set to None if scope_id (nullable) is None
        # and model_fields_set contains the field
        if self.scope_id is None and "scope_id" in self.model_fields_set:
            _dict['scope_id'] = None

        # set to None if scope_value (nullable) is None
        # and model_fields_set contains the field
        if self.scope_value is None and "scope_value" in self.model_fields_set:
            _dict['scope_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WithAttributionModelAccessPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_by_email": obj.get("created_by_email"),
            "created_by_name": obj.get("created_by_name"),
            "created_by_user_id": obj.get("created_by_user_id"),
            "last_change_note": obj.get("last_change_note"),
            "last_modified_at": obj.get("last_modified_at"),
            "last_modified_by_email": obj.get("last_modified_by_email"),
            "last_modified_by_name": obj.get("last_modified_by_name"),
            "last_modified_by_user_id": obj.get("last_modified_by_user_id"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "policy_type": obj.get("policy_type"),
            "scope_id": obj.get("scope_id"),
            "scope_type": obj.get("scope_type"),
            "scope_value": obj.get("scope_value"),
            "targets": [ModelAccessTarget.from_dict(_item) for _item in obj["targets"]] if obj.get("targets") is not None else None,
            "traffic_type": obj.get("traffic_type")
        })
        return _obj


